MCR-2242 MCRPI doesnt need to check write rights if object if is not updated
MyCoRe-Org/mycore pull request #1015
Opened 2020-06-19 11:21 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-2242).

2020-06-19 13:57 UTC, kkrebs approved these changes

2020-06-19 13:57 UTC, kkrebs commented
successfully tested with MIR

2020-06-23 06:56 UTC, yagee-de requested changes

2020-06-23 06:56 UTC, yagee-de commented on mycore-pi/src/main/java/org/mycore/pi/MCRPIService.java
> +
Please correct your code formatter

2020-06-23 17:44 UTC, yagee-de approved these changes

2020-06-23 18:07 UTC, merged