MCR-2262 support requestHandler in solr uri
MyCoRe-Org/mycore pull request #1043
Opened 2020-07-21 09:50 UTC by Possommi

[Link to jira](https://mycore.atlassian.net/browse/MCR-2262).

2020-07-29 11:58 UTC, yagee-de requested changes

2020-07-29 11:58 UTC, yagee-de commented on mycore-solr/src/main/java/org/mycore/solr/common/xml/MCRSolrQueryResolver.java
> + *  solr:q=%2BobjectType%3Ajpjournal
please provide an example for requestHandler

2020-07-29 11:58 UTC, yagee-de commented on mycore-solr/src/main/java/org/mycore/solr/common/xml/MCRSolrQueryResolver.java
> +
please fix import order

2020-07-29 11:58 UTC, yagee-de commented on mycore-solr/src/main/java/org/mycore/solr/search/MCRSolrURL.java
> +import org.apache.solr.client.solrj.impl.HttpSolrClient;
pleas fix import order

2020-07-30 11:52 UTC, yagee-de approved these changes
looks OK to me
Should we merge it to 2020.06.x?

2020-07-31 06:12 UTC, Possommi commented
> Should we merge it to 2020.06.x?
not necessarily

2020-08-13 09:52 UTC, merged