MCR-2295 add cli command(s) to check metadata against schema
MyCoRe-Org/mycore pull request #1082
Opened 2020-10-09 16:49 UTC by OPNA2608

[Link to jira](https://mycore.atlassian.net/browse/MCR-2295).

2020-10-09 17:00 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            e.printStackTrace();
Please use the LOGGER for stacktraces from exceptions and not e.printStackTrace()

2020-10-14 10:37 UTC, sebhofmann requested changes

2020-10-14 10:37 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        for (String objID : idList) {
You could use a for loop with an index if you need a count.
for(int i counter=0;i<maxresults;counter++)

2020-10-14 10:37 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            LOGGER.error("Requested base ID {} not found in store.", baseID);
It would be good if you also add the exception to the .error method.

2020-10-14 10:37 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +    public static void validateObjectsOfType(String type) {
If you dont use anything returned from the validateObject method, then its better to just return a list of commands which should be executed. MyCoRe will then execute these commands. The command org.mycore.frontend.cli.MCRObjectCommands#deleteAllObjects is a good example. 
 
You could also let the validateObject method throw an exception. MyCoRe puts all failed commands to a .txt file in the home directory. You then have a list of a failed objects. You can fix them and then run the command list with "process <txtfile>".

2020-10-23 12:23 UTC, bt1cu requested changes

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        syntax = "validate objects of base {0}",
```suggestion
        syntax = "validate object schema for base {0}",
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            LOGGER.info("Adding " + objID + " to list of objects to validate.");
```suggestion
            LOGGER.debug("Adding " + objID + " to list of objects to validate schema.");
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            cmds.add("validate object " + objID);
```suggestion
            cmds.add("validate object schema for ID " + objID);
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        syntax = "validate objects of type {0}",
```suggestion
        syntax = "validate object schema for type {0}",
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            LOGGER.info("Adding " + objID + " to list of objects to validate.");
```suggestion
            LOGGER.debug("Adding " + objID + " to list of objects to validate schema.");
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            cmds.add("validate object " + objID);
```suggestion
            cmds.add("validate object schema for ID " + objID);
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        syntax = "validate object {0}",
```suggestion
        syntax = "validate object schema for ID {0}",
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        syntax = "validate object {0} after transformer {1}",
```suggestion
        syntax = "validate object schema for ID {0} after transformer {1}",
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            + "after being transformed through {1}-object.xsl.",
should be any transformer script (name)

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        }
```suggestion
LOGGER.debug("Transformer {} has been loaded", transformerType);
                }
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        MCRXMLMetadataManager mgr = MCRXMLMetadataManager.instance();
```suggestion
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        }
```suggestion
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        }
```suggestion
        }
        if (doc == null) {
            throw new MCRException("Could not get object " +  objID.toString() + " from XML store");
        }
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        }
```suggestion
        }
        LOGGER.info("validate object schema for ID " + objectID);
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            doValidateObjectAgainstSchema(objID, trafo);
```suggestion
            doValidateObjectAgainstSchema(objID, trafo);
            LOGGER.info("Object {} successfully validated.", objectID);
```

2020-10-23 12:23 UTC, bt1cu commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +        LOGGER.info("Object {} successfully validated.", objectID);
```suggestion
```

2020-10-23 13:10 UTC, OPNA2608 commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            + "after being transformed through {1}-object.xsl.",
Resolved in https://github.com/MyCoRe-Org/mycore/pull/1082/commits/9c348205f63e2f48fe9420ff6a2a4f3b009ea63e.

2020-10-27 07:11 UTC, bt1cu approved these changes

2020-11-05 08:02 UTC, sebhofmann approved these changes

2020-11-05 08:05 UTC, merged