MCR-2315 Common methods for {base,type,project} CLI command variants
MyCoRe-Org/mycore pull request #1117
Opened 2020-11-19 09:06 UTC by OPNA2608

[Link to jira](https://mycore.atlassian.net/browse/MCR-2315).

Includes trivial migrations of various commands to these new helper methods.

2020-11-23 11:56 UTC, yagee-de commented
Please add Javadoc to public methods of MCRCommandUtils

2021-01-04 12:42 UTC, yagee-de commented
It is already in a good shape, but I think it does not use Java-Features well enough.
There should be helper methods to generate Stream instances for different types, baseIds and from-to-intervalls, and what ever is necessary to get those streams generated. Then we should use `Function<String, String>` to map single values to a command. That would help to get rid of `String... otherValues` as this is moved to a lambda expression.


```java

//example now
return MCRCommandUtils.runCommandOnBaseId("repair metadata search of ID {0}", baseID);
//example later
return MCRCommandUtils.getIdsForBaseId(base)
    .map(id -> "repair metadata search of ID "+id)
    .collect(Collectors.toList());
```

This will make the calls more readable as the command is clear instead of splitting it over several parameters, if `otherValues` is used.

2021-01-15 12:29 UTC, OPNA2608 commented
@yagee-de Could you take another look please? I dropped the `runCommandOn` methods in favour of using the `getIdsFor` ones everywhere like in your code example.

2021-01-19 10:47 UTC, yagee-de requested changes

2021-01-19 10:47 UTC, yagee-de commented on mycore-pi/src/main/java/org/mycore/pi/doi/cli/MCRDOICommands.java
> +            }).map(MCRDigitalObjectIdentifier::asString).map(id -> syntaxMF.format(new Object[] { id }))
Does not seem to provide the right amount of parameters. Why the change?

2021-01-19 10:47 UTC, yagee-de commented on mycore-mods/src/main/java/org/mycore/mods/MCRMODSCommands.java
> +            .map(file -> "load mods document from file " + file + " for project " + projectID)
Why the change?

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        if (idList.size() == 0) {
use isEmpty()

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        if (idList.size() == 0) {
use isEmpty()

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        if (idList.size() == 0) {
use isEmpty()

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +            throw new MCRUsageException("Requested type " + type + " not found!", e);
Do not throw an exception here! Never ever catch RuntimeException if you cannot handle them.

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +            throw new MCRUsageException("Start-ID " + startId + " is invalid!", e);
Do not catch this exception here.

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        } catch (MCRException e) {
..or here

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +            throw new MCRUsageException(
Do not catch a RuntimeException if you cannot handle it.

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        }
Only require a property, if you use it. Code you call later may change and requires to check the input data. Do not duplicate checks!

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        if (base == null || base.length() == 0) {
If you want to check a valid "base" here check for "_" oder use MCRObjectID.getIDParts()

2021-01-19 10:47 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        } catch (ArrayIndexOutOfBoundsException e) {
do not catch RuntimeException here, code may change and will leave this code dead here.

2021-01-19 14:29 UTC, OPNA2608 commented on mycore-mods/src/main/java/org/mycore/mods/MCRMODSCommands.java
> +            .map(file -> "load mods document from file " + file + " for project " + projectID)
Fallout from the `runCommandOn` removal, will drop the change.

2021-01-19 14:29 UTC, OPNA2608 commented on mycore-pi/src/main/java/org/mycore/pi/doi/cli/MCRDOICommands.java
> +            }).map(MCRDigitalObjectIdentifier::asString).map(id -> syntaxMF.format(new Object[] { id }))
Same fallout, will drop.

2021-01-27 14:52 UTC, yagee-de commented
It's hard to start from scratch every review. Please consider adding single commits in the future.

2021-01-27 15:00 UTC, yagee-de requested changes
Do not return parallelStreams by default. Will cause issues with session management and database connections.

2021-01-27 15:00 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        return idList.parallelStream();
use stream() not parallelStream()

2021-01-27 15:00 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        return idList.parallelStream();
use stream() not parallelStream()

2021-01-27 15:00 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandUtils.java
> +        return idList.parallelStream();
use stream() not parallelStream()

2021-01-28 07:30 UTC, yagee-de approved these changes

2021-01-28 07:31 UTC, merged