MCR-2333-commands_to_process_commands_file_from_Classpath
MyCoRe-Org/mycore pull request #1137
Opened 2021-01-22 14:45 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-2333).

2021-01-22 15:20 UTC, rsteph-de approved these changes
looks good for me

2021-01-27 14:50 UTC, yagee-de requested changes

2021-01-27 14:50 UTC, yagee-de commented on mycore-webcli/src/main/java/org/mycore/webcli/cli/MCRBasicWebCLICommands.java
> +    @MCRCommand(syntax = "process from resources {0}", help = "Execute the commands listed in the resource file {0}.",
"process from resources foo/bar/setup.txt" --> "process resource foo/bar/setup.txt"

2021-01-27 14:50 UTC, yagee-de commented on mycore-webcli/src/main/java/org/mycore/webcli/cli/MCRBasicWebCLICommands.java
> +    public static List<String> readCommandsResource(String resource) throws IOException, URISyntaxException {
URISysntaxException is never thrown

2021-01-27 14:50 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandLineInterface.java
> +            return Collections.emptyList();
Should throw an IOException here if the resource is not found.

2021-01-27 14:50 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandLineInterface.java
> +            try (BufferedReader reader = new BufferedReader(new InputStreamReader(is, Charset.defaultCharset()))) {
Better link Autoclosables in one line
`try (InputStream is=..; InputStreamReader ir=...; BufferedReader reader=...)`
Consider NOT using "`defaultCharset()`" for resources but use a defined one like `StandardCharsets.UTF_8`

2021-02-19 14:06 UTC, yagee-de requested changes

2021-02-19 14:06 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandLineInterface.java
> +
please fix import order

2021-02-19 14:06 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRCommandLineInterface.java
> +            new InputStreamReader(resourceURL.openStream(), Charset.defaultCharset()))) {
may leak resourceURL.openStream() and do not use defaultCharset() for classpath resources but stick it to UTF8 from StandardCharsets class

2021-02-19 14:41 UTC, yagee-de approved these changes

2021-02-19 16:41 UTC, merged