MCR-2339 login ArrayIndexOutOfBoundException if you enter a Username with @ as last char
MyCoRe-Org/mycore pull request #1174
Opened 2021-02-18 10:11 UTC by OPNA2608

[Link to jira](https://mycore.atlassian.net/browse/MCR-2339).

2021-02-18 10:50 UTC, yagee-de requested changes
I do not think we should allow an empty realmId here
if `parts.length != 2` throw IllegalArgumentException here

2021-02-18 11:09 UTC, sebhofmann commented
> I do not think we should allow an empty realmId here
> if `parts.length != 2` throw IllegalArgumentException here

Also second "@" is possible.

2021-02-18 12:31 UTC, OPNA2608 commented
> if `parts.length != 2` throw IllegalArgumentException here

I don't think replacing one MyCoRe kernel exception screen with a slightly different one is the best UX solution here.

![Bildschirmfoto von 2021-02-18 12-17-25](https://user-images.githubusercontent.com/23431373/108349796-b732b280-71e3-11eb-9a0c-2e749cbcec18.png)

---

What if I do this instead:
```java
if (parts.length == 2) {
    return getUser(parts[0], parts[1]);
} else {
    return null;
}
```

Since `checkPassword` checks for `getUser(userName) == null` anyway in case one of the later checks returns negative, that should work without pushing an empty realmId through the realm checking code.

2021-02-19 14:09 UTC, yagee-de approved these changes

2021-02-19 14:10 UTC, merged