MCR-2379 MCRCronjob
MyCoRe-Org/mycore pull request #1205
Opened 2021-03-16 17:30 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-2379).

Change the base to main if MCR-2359 is merged

2021-03-31 12:34 UTC, sebhofmann commented on mycore-cronjob/pom.xml
> +      <scope>compile</scope>
remove this

2021-03-31 12:48 UTC, rsteph-de commented on mycore-cronjob/src/main/resources/META-INF/persistence.xml
> +<?xml version="1.0" encoding="UTF-8" ?>
move to src/test/resources folder

2021-03-31 12:53 UTC, yagee-de requested changes

2021-03-31 12:53 UTC, yagee-de commented on mycore-cronjob/src/main/java/org/mycore/mcr/cronjob/MCRCronStarter.java
> +        MCRCronjobManager.getInstance().startUp();
compare if `servletContext != null` so that cron job are only available in web context

2021-04-15 14:45 UTC, rsteph-de approved these changes
looks good for me

2021-04-15 15:22 UTC, merged