MCR-2398 MCRXMLMetadataManager Interface
MyCoRe-Org/mycore pull request #1234
Opened 2021-04-27 12:07 UTC by OPNA2608

[Link to jira](https://mycore.atlassian.net/browse/MCR-2398).

Still need to test & find a good solution for code calling `MCRXMLMetadataManager.instance()` directly vs `MCRAbstractXMLMetadataManager.getManager()` reading the configured XML Metadata Manager class and instantiating it via its `instance()` method.

2021-04-29 12:27 UTC, OPNA2608 commented
Gonna look over code comments again, otherwise ready for review.

2021-04-29 15:13 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/datamodel/common/MCRXMLMetadataManager.java
> + * store & manage local SVN repositories:
error: bad HTML entity:
* store & manage local SVN repositories:

2021-04-30 06:38 UTC, OPNA2608 commented on mycore-base/src/main/java/org/mycore/datamodel/common/MCRXMLMetadataManager.java
> + * store & manage local SVN repositories:
Fixed, thanks.

2021-06-04 11:32 UTC, yagee-de approved these changes
Looks good as the next step for me. But I think one refactoring would be useful:

- move all abstract methods to an interface and let MCRDefaultXMLMetadataManager inherit this interface and remove the superclass from MCRDefaultXMLMetadataManager
- make abstract methods public and delegate to the interface methods

Interfaces are a better preparation for java modules

2021-06-08 12:13 UTC, OPNA2608 commented
I've dropped all commits that were unrelated to the ticket's goal. I'll move them into a follow-up PR once this is merged.

2021-06-17 10:36 UTC, sebhofmann requested changes
Everything else looks good for me.

2021-06-17 10:36 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/datamodel/common/MCRXMLMetadataManager.java
> +            IMPLEMENTATION = MCRConfiguration2
The Property MCR.Metadata.Manager.Class should be defined in the mycore.properties.
We have the Rule that every default property should be in the mycore.properties, except for dynamic named properties.

2021-06-17 15:58 UTC, sebhofmann approved these changes

2021-06-18 06:52 UTC, merged