MCR-2439 read and change object state via rest api
MyCoRe-Org/mycore pull request #1278
Opened 2021-07-14 08:25 UTC by yagee-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-2439).

2021-07-14 10:02 UTC, kkrebs requested changes
for details see comment in jira ticket

2021-07-14 16:35 UTC, kkrebs commented
there are conflicts, please rebase branch and solve conflicts

2021-08-05 13:22 UTC, rsteph-de requested changes
License header and Javadocs on new files are missing!

2021-08-05 13:22 UTC, rsteph-de commented on mycore-restapi/src/main/java/org/mycore/restapi/MCRApiDraftFilter.java
> +package org.mycore.restapi;
License Header?

2021-08-05 13:22 UTC, rsteph-de commented on mycore-restapi/src/main/java/org/mycore/restapi/MCRApiDraftFilter.java
> +@Priority(Priorities.AUTHORIZATION)
JavaDoc?

2021-08-05 13:22 UTC, rsteph-de commented on mycore-restapi/src/main/java/org/mycore/restapi/annotations/MCRApiDraft.java
> +package org.mycore.restapi.annotations;
License Header

2021-08-17 14:57 UTC, rsteph-de approved these changes
looks good for me now!

2021-08-17 15:00 UTC, kkrebs approved these changes

2021-08-17 15:01 UTC, merged