MCR-2482 option to enable access key strategy explicit for objects or derivates
MyCoRe-Org/mycore pull request #1347
Opened 2021-09-24 12:41 UTC by golsch

[Link to jira](https://mycore.atlassian.net/browse/MCR-2482).

2021-09-28 13:29 UTC, kkrebs requested changes

2021-09-28 13:29 UTC, kkrebs commented on mycore-acl/src/main/resources/components/acl/config/mycore.properties
> +MCR.ACL.AccessKey.Strategy.AllowedObjectTypes=object
please disable properties per default and change "object" to "mods" or "document"

2021-09-28 14:10 UTC, sebhofmann approved these changes

2021-09-28 16:46 UTC, rsteph-de approved these changes
modified default properties are O.K.
(solved as discussed in telco)

2021-09-29 06:47 UTC, kkrebs approved these changes

2021-09-29 06:48 UTC, merged