MCR-2507 Add touch commands
MyCoRe-Org/mycore pull request #1363
Opened 2021-11-15 14:01 UTC by toKrause

[Link to jira](https://mycore.atlassian.net/browse/MCR-2507).

2021-11-15 15:38 UTC, kkrebs requested changes
We should think more deeply about this pull request. Do we need this command additional to our existing repair commands? What is the added value?

2021-11-15 15:38 UTC, kkrebs commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRDeveloperCommands.java
> +            MCRMetadataManager.update(object);
the repair command calls here:
MCRMetadataManager.fireRepairEvent(obj);

So in difference to our repair commands not only all event handlers are fired again. The additional code handling the structure section is also running in this case.

2021-11-16 09:14 UTC, toKrause commented
Could we leave the discussion at a single location (JIRA issue or here)? Otherwise it gets really confusing.

Yes, the proposed command does more than firing an "repair event"; exactly my point. The whole point of this _developer command_ is to _perform an update_, with everything that is part of that process. This is helpful during debugging or to check the impacts of modifications to the software. If it would only fire an event, something important might be left out. 

Also, again, an "update event" is presumably or at least potentially handled differently then a "repair event", so i still don't understand what the repair events and the repair commands have to do with the proposed commands.

2021-11-29 16:23 UTC, sebhofmann approved these changes

2021-11-30 13:09 UTC, yagee-de approved these changes

2021-11-30 13:23 UTC, merged