MCR-2508 Extend existing commands to allow importing of unknown objects and derivates
MyCoRe-Org/mycore pull request #1365
Opened 2021-11-15 14:52 UTC by toKrause

[Link to jira](https://mycore.atlassian.net/browse/MCR-2508).

2021-11-15 15:32 UTC, kkrebs commented
We now have several places in our code to deal with zero IDs. Perhaps this should be part of the MCRMetadataManager.create() method?! So we have to add the same code every time before we call create():
- REST-API
- MCRCreateObjectServlet
- and now also via CLI

2021-11-16 08:54 UTC, toKrause commented
This certainly sounds like a good idea. Could this be al follow-up or should I update the Jira issue and modify this PR?

2021-11-16 09:16 UTC, kkrebs commented
update the Jira issue and modify this PR would be great. It should be no problem to leave the zero id code in REST-API and MCRCreateObjectServlet for now. We could clean the code as part of an follow up ticket. But we should not add more ...

2021-11-16 12:24 UTC, toKrause commented
I've moved the code and made some minor cleanup. A followup issue should be created when this PR is merged.

2021-11-16 12:24 UTC, toKrause commented
I've notices that almost all calls to static methods of `MCRMetadataManager` inside of `MCRMetadataManager` are unnecessarily qualified (i.e. `MCRMetadataManager.create(mcrDerivate);`). Is that a local style that should be adhered to?

2021-11-29 16:29 UTC, sebhofmann requested changes

2021-11-29 16:29 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/datamodel/metadata/MCRMetadataManager.java
> +            objectId = MCRObjectID.getNextFreeId(objectId.getBase(), objectId.getTypeId());
I think this has to be .getNextFreeId(objectId.getProjectId(), ...

Also the parameter name of getNextFreeId is wrong. It should be projectIid

2021-12-02 09:45 UTC, toKrause commented
Sorry, changed the wrong PR to draft.

2021-12-06 08:43 UTC, sebhofmann approved these changes

2021-12-06 09:35 UTC, merged