Issues/mcr 2522 allow to limit user selection to particular name identifier type
MyCoRe-Org/mycore pull request #1383
Opened 2021-11-26 15:00 UTC by chemicus

[Link to jira](https://mycore.atlassian.net/browse/MCR-2522).

2021-12-05 19:53 UTC, fluetze reviewed
Could you please explain, here or in the Jira ticket, why one might wish to limit a match to only certain name identifier types? If so, wouldn't it be better to be able to specify more than one type, and not just one or all?

2021-12-06 10:59 UTC, chemicus commented
In the current implementation all nameIdentifiers are used, regardless of being verified or not. The ORCID guidelines require, however, that users need to approve that a work that has been assigned to them, really "belongs" to them. Therefore we should only sync publications where the mods:nameIdentifier[@type='orcid'] has been set, thus the need to limit the type(s) of identifier(s).
I do not see a necessity to limit to more than one identifier at the moment, although one could think about that of course. A general solution would be more complicated, however, since the boolean operator (and, or, ...) between different identifiers would need to be specified as well.
I would therefore suggest to accept the current modification for now, since this is already an improvement. If we see a need for a more general solution, I can certainly add that later.

2021-12-06 11:53 UTC, fluetze reviewed
Refactoring ok?

2021-12-06 12:30 UTC, chemicus commented
Look ok to me!

2021-12-06 12:30 UTC, fluetze submitted a review, later dismissed

2021-12-06 13:03 UTC, rsteph-de requested changes, later dismissed
Build failed!

2021-12-06 13:03 UTC, rsteph-de commented on mycore-orcid/src/main/java/org/mycore/orcid/user/MCRORCIDUser.java
> +        List<Element> nameIdentifiers = wrapper.getElements(xPath));
Syntax error - because of doubled ")" at the end !!!

2021-12-06 13:35 UTC, fluetze approved these changes, later dismissed

2021-12-09 07:30 UTC, kkrebs approved these changes

2021-12-09 07:30 UTC, merged