MCR-2608 Support new dnb urn service api
MyCoRe-Org/mycore pull request #1509
Opened 2022-04-05 07:40 UTC by Possommi

[Link to jira](https://mycore.atlassian.net/browse/MCR-2608).

2022-04-05 19:25 UTC, kkrebs requested changes
please fix codacy and javadoc error

2022-04-05 19:25 UTC, kkrebs commented on mycore-pi/src/main/java/org/mycore/pi/urn/rest/MCRDNBURNRestClient.java
> + * <br/> <br/>
this leads to javadoc errors
Error:  /home/runner/work/mycore/mycore/mycore-pi/src/main/java/org/mycore/pi/urn/rest/MCRDNBURNRestClient.java:49: error: self-closing element not allowed
Error:   * <br/> <br/>

2022-04-21 07:32 UTC, sebhofmann approved these changes

2022-04-25 07:25 UTC, kkrebs approved these changes

2022-04-25 07:26 UTC, merged