MCR-2635 MCRJanitorEventHandlerBase should always switch back user information
MyCoRe-Org/mycore pull request #1526
Opened 2022-04-26 09:19 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-2635).

2022-04-26 13:15 UTC, yagee-de approved these changes
MCRJanitorEventHandler should use executor service or alike to get the job done. But this PR fixes the issue.

2022-04-26 13:55 UTC, yagee-de commented
please add mycore java header

2022-04-27 07:37 UTC, kkrebs requested changes
#

2022-04-27 13:47 UTC, kkrebs approved these changes

2022-04-27 15:20 UTC, merged