MCR-2604 OCFL Classification Storage
MyCoRe-Org/mycore pull request #1546
Opened 2022-05-10 12:07 UTC by Hammer1279

This adds a Classification Storage in a OCFL Repository, while the Database handles access to the files, the OCFL Store works like a backup and stores changes versioned. 

In additon, to work, this also brings an DAO Implementation with added Events and a ClassificationManager Interface.

[Link to jira](https://mycore.atlassian.net/browse/MCR-2604).

2022-05-16 05:16 UTC, Hammer1279 commented
Docs can be found here: https://github.com/MyCoRe-Org/mycore-website/blob/ocfl-class/mycore.org/content/de/documentation/basics/basics_mcr_ocfl.md

2022-05-24 06:59 UTC, yagee-de requested changes

2022-05-24 06:59 UTC, yagee-de commented on mycore-ocfl/src/main/java/org/mycore/ocfl/MCROCFLPersistenceTransaction.java
> +        if (verboseLogging) {
LOGGER.debug already checks if Specific logger is on debug level. No need to specify any property or adding custom checks

2022-05-24 06:59 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/datamodel/classifications2/impl/MCREventedCategoryDAOImpl.java
> +        ((ArrayList<MCREvent>) currentSession.get(classQueue)).add(evt);
String "classQueue" is used to often in Code. This should be centralized somewhere.
Also a BIG no go is to use session as a storage for transactional data without any transactional reference. There could be two different transactions running concurrently and one is rolled back. In this case all the data of two transactions are lost.

2022-05-24 06:59 UTC, yagee-de commented on mycore-ocfl/src/main/java/org/mycore/ocfl/MCROCFLXMLClassificationManager.java
> +        MCREvent event = (MCREvent) evt.get("event");
Do not use magic Strings here. Make them "public static final" somewhere and document them. What is that "event" within an event anyway?

2022-05-24 06:59 UTC, yagee-de commented on mycore-ocfl/src/main/resources/components/ocfl/config/mycore.properties
> +
please: no!

2022-05-24 07:16 UTC, yagee-de commented
Properties of a transaction are:

- Atomicity
- Consistency
- Isolation
- Durability

Atomicity is hard to achieve on a filesystem storage, we could rollback to a previous version. So not that big of a deal.
Consistency seems no to be harmed by this PR.
Isolation is currently weakened as any change is visible to any other user in a mutable directory and transaction commits data from other transactions within the same session. Also different transaction could write to the same resource.
Durability is due to ocfl.

2022-05-24 07:21 UTC, yagee-de commented
You could keep your data in a transaction object and have that transaction being committed later. If you NEED to use a mutable HEAD of an OCFL object, make sure to acquire a lock to operate on that. That lock should belong to the transaction and if the transaction is committed than "commitStagedChanges" on that object. If a rollback occurs, free the lock after you "purgeStagedChanges".

2022-05-24 07:24 UTC, yagee-de commented
Thanks for your documentation and your work. I really appreciate your push towards a OCFL storage option.

2022-06-17 08:53 UTC, yagee-de requested changes

2022-06-17 08:53 UTC, yagee-de commented on mycore-ocfl/src/main/java/org/mycore/ocfl/commands/MCROCFLDevCommands.java
> +        }
Does not use OCFL-API and requires a specific non-default storage layout

2022-06-17 08:53 UTC, yagee-de commented on mycore-ocfl/src/main/java/org/mycore/ocfl/MCROCFLXMLClassificationManager.java
> +    }
Where are all these files come from? Where is this specified? How to we ensure that if a classification is deleted all categories are deleted, too?

2022-06-17 08:53 UTC, yagee-de commented on mycore-ocfl/src/main/java/org/mycore/ocfl/MCROCFLXMLClassificationManager.java
> +    public void fileDelete(MCRCategoryID mcrid) {
method naming: We have "create", "update" and "fileDelete". Should be renamed to "delete"

2022-06-17 08:55 UTC, yagee-de commented
We should have a discussion about messages beeing parsed to determine what action caused a revision. This does not look good to me.

2022-06-20 07:07 UTC, Hammer1279 commented on mycore-ocfl/src/main/java/org/mycore/ocfl/MCROCFLPersistenceTransaction.java
> +        final MCROCFLXMLClassificationManager ocflClassficationManager = manager;
Why not just change all occurances of `ocflClassificationManager` to `manager`?

2022-06-24 10:05 UTC, yagee-de approved these changes

2022-06-24 10:08 UTC, merged