MCR-2681 update derivate metadata (titles, classification, maindoc)
MyCoRe-Org/mycore pull request #1599
Opened 2022-06-24 12:14 UTC by rsteph-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-2681).

2022-06-24 12:39 UTC, yagee-de requested changes

2022-06-24 12:39 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/v2/MCRRestDerivates.java
> +        return doPatchDerivate(derid, der);
please inline

2022-06-24 12:39 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/v2/MCRRestDerivates.java
> +        if (modified) {
isn't it fixed to true?

2022-07-27 13:01 UTC, rsteph-de commented on mycore-restapi/src/main/java/org/mycore/restapi/v2/MCRRestDerivates.java
> +        if (modified) {
modified variable now initialized with 'false'

2022-08-30 12:40 UTC, yagee-de approved these changes

2022-08-30 12:41 UTC, merged