MCR-2684 RestAPIv2: JSON serialization for objects and derivates
MyCoRe-Org/mycore pull request #1603
Opened 2022-06-28 09:56 UTC by rsteph-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-2684).

2022-06-28 10:04 UTC, yagee-de reviewed
JSON output should be done via Transformer and is already handled via `org.mycore.restapi.converter.MCRContentAbstractWriter`. But we could include a transformer for MCRDerivate. Feel free to submit on with this PR

2022-06-28 10:05 UTC, yagee-de commented
We could also include a Transformer for handling your case, that `MCRObject.createJSON()` is enough.

2022-06-28 13:45 UTC, rsteph-de commented
works now with MCRContentWriter and new MCRContentTransformers to create JSON from MCRObjects and MCRDerivates

2022-06-28 13:55 UTC, yagee-de requested changes

2022-06-28 13:55 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/common/content/transformer/MCRBase2JSONTransformer.java
> +            MCRBase mcrBase = MCRMetadataManager.retrieve(mcrId);
You should use the content provided not read it again.

2022-06-28 14:49 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/common/content/transformer/MCRBase2JSONTransformer.java
> +            MCRBase mcrBase = MCRMetadataManager.retrieve(mcrId);
solved with new ContentTransformers vor MCRObject and MCRDerivate

2022-06-29 12:02 UTC, yagee-de approved these changes
:+1: looks very good

2022-06-29 12:06 UTC, merged