MCR-2707 inital proposal
MyCoRe-Org/mycore pull request #1632
Opened 2022-07-21 16:31 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-2707).

2022-07-27 13:25 UTC, yagee-de requested changes

2022-07-27 13:25 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntity.java
> +    }
Should be MCRObjectID not String.

2022-07-27 13:25 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntity.java
> +    }
the getter should use the methods of MCRObjectID

2022-07-27 13:26 UTC, yagee-de commented
Still not done with review but a first suggestion. Sorry

2022-09-02 13:59 UTC, yagee-de commented
We need more JUnit test and javadocs

2022-09-08 11:27 UTC, yagee-de requested changes

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntity.java
> +public class MCRObjectEntity {
Naming? MCRObjectInfo was a suggestion

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntityCommands.java
> +public class MCRObjectEntityCommands {
rename accordingly

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntityEventHandler.java
> +public class MCRObjectEntityEventHandler extends MCREventHandlerBase {
rename accordingly

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntityEventHandler.java
> +public class MCRObjectEntityEventHandler extends MCREventHandlerBase {
Add Javadoc

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntityManager.java
> +public class MCRObjectEntityManager {
rename accordingly
add Javadoc

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntityManager.java
> +    public static void delete(MCRObject object, Instant deletedDate, String deletedBy) {
Only public method is to delete?

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectEntityQueryResolver.java
> +public class MCRObjectEntityQueryResolver implements MCRObjectQueryResolver {
rename accordingly and add Javadocs and JUnit tests

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectIDPK.java
> +public class MCRObjectIDPK implements Serializable {
Javadocs ;-)

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/datamodel/common/MCRObjectQuery.java
> +public class MCRObjectQuery {
Javadocs \@see ThisOtherClass

2022-09-08 11:27 UTC, yagee-de commented on mycore-base/src/main/resources/config/mycore.properties
> +  MCR.EventHandler.MCRObject.020A.Class=org.mycore.backend.jpa.MCRObjectEntityEventHandler
Anything better than officially use 020A? Do we have space left?

2022-09-12 08:28 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/backend/jpa/MCRObjectIDPK.java
> +public class MCRObjectIDPK implements Serializable {
You wrote that Class: https://github.com/MyCoRe-Org/mycore/pull/1632/commits/b69cc1f992de52bdda4a798f3c93493511db76ee

2022-09-20 08:18 UTC, closed without merging