MCR-2742 New ids found during enrichment are added to the idPool befo…
MyCoRe-Org/mycore pull request #1681
Opened 2022-09-26 10:24 UTC by chemicus

…re the mods merge, which can lead to duplicate source requests

[Link to jira](https://mycore.atlassian.net/browse/MCR-2742).

2022-09-26 11:18 UTC, fluetze approved these changes

2022-10-11 12:07 UTC, fluetze approved these changes

2022-10-11 12:28 UTC, fluetze requested changes
Still examining the changed test behaviour...

2025-11-26 14:44 UTC, sebhofmann commented
This is stale for over 3 years so i close it now.

2026-02-11 10:32 UTC, kkrebs commented
No longer relevant and largely fixed with MCR-2893

2026-02-11 10:32 UTC, closed without merging