MCRURNUtils.getDNBRegisterDate now use URN REST-API V2
MyCoRe-Org/mycore pull request #1773
Opened 2022-12-16 07:35 UTC by chiliego

[Link to jira](https://mycore.atlassian.net/browse/MCR-2808).

2023-01-17 15:05 UTC, sebhofmann requested changes
Please make MCRDNBURNRestClient usable without a bundleProvider or make getRegistrationInfo static.

2023-02-01 14:27 UTC, chiliego commented
@sebhofmann can you explain your comment in more detail, why "make MCRDNBURNRestClient usable without a bundleProvider or make getRegistrationInfo static"?

2023-02-01 15:43 UTC, sebhofmann requested changes

2023-02-01 15:43 UTC, sebhofmann commented on mycore-pi/src/main/java/org/mycore/pi/urn/rest/MCRDNBURNRestClient.java
> +        String url = mcrurnClient.getBaseServiceURL() + "/urn/" + identifier;
The method getBaseServiceURL() does not rely on any field of the class so you could make it static or add a static variant which is used by the non static version.

2023-02-01 15:43 UTC, sebhofmann commented on mycore-pi/src/main/java/org/mycore/pi/urn/rest/MCRDNBURNRestClient.java
> +                mcrurnClient.logFailure("", response, statusCode, identifier, url);
The method logFailure() does not rely on any field of the class so you could make it static or add a static variant which is used by the non static version.

2023-02-01 15:43 UTC, sebhofmann commented on mycore-pi/src/main/java/org/mycore/pi/urn/rest/MCRDNBURNRestClient.java
> +        MCRDNBURNRestClient mcrurnClient = new MCRDNBURNRestClient(
If you make some other methods static you can remove the instance of the class and the weird constructor call is not needed.

2023-02-02 09:27 UTC, sebhofmann approved these changes
apart from the codacy errors the changes looks good now

2023-02-03 10:18 UTC, kkrebs commented
please fix forbidden api error
Error:  Forbidden method invocation: java.io.InputStreamReader#<init>(java.io.InputStream) [Uses default charset]
Error:    in org.mycore.pi.urn.rest.MCRDNBURNRestClient (MCRDNBURNRestClient.java:181)
Error:  Scanned 107 class file(s) for forbidden API invocations (in 0.21s), 1 error(s).

... see build log

2023-02-06 11:14 UTC, merged