MCR-2840 URN registering not working
MyCoRe-Org/mycore pull request #1805
Opened 2023-02-12 14:57 UTC by chiliego

[Link to jira](https://mycore.atlassian.net/browse/MCR-2840).

2023-02-14 14:07 UTC, yagee-de commented
please re-format code

2023-03-02 06:39 UTC, yagee-de commented on mycore-pi/src/main/java/org/mycore/pi/urn/rest/MCRDerivateURNUtils.java
> +                            + filePath.replaceAll(" ", "%20"));
Do not URL encode like this. There will be more cases of characters that need to be percent encoded.

2023-03-03 07:42 UTC, Possommi approved these changes

2023-03-14 14:43 UTC, kkrebs requested changes
some of this changes are not compatible with 2022.06 and not needed to fix this problem
please minimize this commit to make a merge to 2022.06 possible without a lot of conflicts
renaming eg. should be done in 2022.06 or main

please also resolve comment from yagee

2023-03-28 14:22 UTC, chiliego commented
> some of this changes are not compatible with 2022.06 and not needed to fix this problem please minimize this commit to make a merge to 2022.06 possible without a lot of conflicts renaming eg. should be done in 2022.06 or main

Please tell me which changes are not compatible with 2022.06, so I can make adjustments.

2023-03-29 07:01 UTC, chiliego commented
> some of this changes are not compatible with 2022.06 and not needed to fix this problem please minimize this commit to make a merge to 2022.06 possible without a lot of conflicts renaming eg. should be done in 2022.06 or main
> 

When merge with 2022.06.x I can see 3 conflicting files: MCRDNBURNRestClient.java, MCRURNGranularRESTRegistrationTask.java and MCRURNGranularRESTServiceTest.java. 

The conflict in MCRURNGranularRESTServiceTest.java comes from changes directly in 2022.06.x, where JMockit was removed and was not introduced by changes in this issue branch.
The conflict in MCRURNGranularRESTRegistrationTask.java is removing two imports which are never used in this class.
 
The changes in MCRDNBURNRestClient.java fix the logs so you can see the real error, which helped me solving the URN registering problem! So this is also a fix!

> please also resolve comment from yagee
is done

2023-05-09 09:29 UTC, closed without merging