MCR-2856 JobQueue improvements
MyCoRe-Org/mycore pull request #1835
Opened 2023-04-20 15:28 UTC by sebhofmann

* avoid naming things like slaveFactory
* reduced complexity of MCRJobManager#run method (MCRJobMaster) and other methods
* moved most configuration options to interface
* added MAX_TRIES status, exception and tries collumns to database
* change job status to MAX_TRIES after they run n times (configurable)
* added commands to list and reset jobs which have job status MAX_TRIES
* removed single queue mode (makes code more complex and nobody should have used it)

[Link to jira](https://mycore.atlassian.net/browse/MCR-2856).

2023-05-23 12:07 UTC, Mewel requested changes
* MCRJobRunnable#run() is to long
* MCRJobRunnable#run() setStatus(MCRProcessableStatus.failed) is never set
* MCRJobThreadStarter constructor is to long -> should use static inner classes for MCRJobQueueEventListener and ThreadPoolExecutor
* MCRTestJobAction class should be moved to test -> maybe rename because there is already one in test
* MCRJobThreadStarterTest#testRun() 87 -> try to avoid waiting in test cases if possible -> this is very annoying for building mycore

minor code improvements:
* some LOGGER's and other member variables maybe final
* MCRJobQueue 226 -> return Collections.emptyIterator();
* MCRJobResetter 45 -> private final Function<Class<?>, Queue<MCRJob>> queueResolver;
* MCRJobThreadStarter 203 -> null check can be removed
* MCRJobDAOJPAImplTest 271 and multiple others -> allJobs.forEach(em::persist);
MCRJobQueueTest 48 -> MCRJobQueueEventListener listener = notifiedJobs::add;

2023-05-23 15:24 UTC, sebhofmann commented
> * MCRJobRunnable#run() is to long

I extracted handleJobExecutionException

> * MCRJobRunnable#run() setStatus(MCRProcessableStatus.failed) is never set

Its set by setError(Throwable method)

> * MCRJobThreadStarter constructor is to long -> should use static inner classes for MCRJobQueueEventListener and ThreadPoolExecutor

Extracted ListenerNotifier, JobThreadFactory and ActiveCountingThreadPoolExecutor to static inner class 

> * MCRTestJobAction class should be moved to test -> maybe rename because there is already one in test
> * MCRJobThreadStarterTest#testRun() 87 -> try to avoid waiting in test cases if possible -> this is very annoying for building mycore

Removed "Production" TestJobAction and related Command

> 
> minor code improvements:
> 
> * some LOGGER's and other member variables maybe final

Set all loggers to final

> * MCRJobQueue 226 -> return Collections.emptyIterator();

Done

> * MCRJobResetter 45 -> private final Function<Class<?>, Queue> queueResolver;

Changed to ? extends MCRJobAction

> * MCRJobThreadStarter 203 -> null check can be removed

Done

> * MCRJobDAOJPAImplTest 271 and multiple others -> allJobs.forEach(em::persist);

Done 

>   MCRJobQueueTest 48 -> MCRJobQueueEventListener listener = notifiedJobs::add;

Done

2023-06-02 09:39 UTC, yagee-de commented on mycore-jobqueue/src/main/java/org/mycore/services/queuedjob/MCRJobRunnable.java
> +            executionException.printStackTrace(pw);
@sonatype-lift ignore

2023-06-02 10:04 UTC, yagee-de approved these changes
change requests from @Mewel applied and added changes for sonatype and organized imports

2023-06-02 12:46 UTC, merged