MCR-2891 Object History Permission
MyCoRe-Org/mycore pull request #1868
Opened 2023-06-12 12:57 UTC by Hammer1279

- add history view check to listRevisions
- add history read check to requestVersionedObject

[Link to jira](https://mycore.atlassian.net/browse/MCR-2891).

2023-06-12 14:03 UTC, Hammer1279 commented on mycore-base/src/main/java/org/mycore/datamodel/common/MCRXMLMetadataManager.java
> +            ? IMPLEMENTATION.listRevisions(id) : Collections.emptyList();
But this is a read only method?

2023-06-14 16:30 UTC, rsteph-de requested changes
Sebastian and I looked into the code, I will add more implementation notes to the JIRA-ticket

2023-06-14 16:30 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/datamodel/common/MCRXMLMetadataManager.java
> +            ? IMPLEMENTATION.listRevisions(id) : Collections.emptyList();
Do not check Permissions in MCRXMLMetadataManager
Permission check should be implemented where the method is called (REST-API, URI-Resolver, MCRObjectServlet, ???)

2023-06-14 16:30 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/frontend/servlets/MCRObjectServlet.java
> +                getErrorI18N(I18N_ERROR_PREFIX, "accessDenied", mcrid.toString() + " " + rev,
use a better name for "accessDenied", something like "accessToVersionDenied"
and provide a proper error message

2023-06-16 07:28 UTC, Hammer1279 commented
I think I'll have to recreate the branch... this looks very wrong...

2023-06-19 06:13 UTC, Hammer1279 commented
Note for the missing i18n for anything except for german and english:
While I am able to edit the i18n, it would ruin the entire formatting of all those files, so I had to edit them by hand instead of with tools.
That raises the question if it is important to have them formatted to be easily human readable if we mostly use tools anyways to edit them or if it is okay to have them all bunched together.

2023-07-04 15:25 UTC, sebhofmann approved these changes

2023-07-04 15:25 UTC, rsteph-de approved these changes
looks good now after final changes  (acl:checkPermission in versions.xml)

2023-07-04 17:28 UTC, merged