MCR-2546 consolidate id generation in MCRCreateObjectServlet
MyCoRe-Org/mycore pull request #1874
Opened 2023-06-13 12:45 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-2546).

2023-06-14 14:03 UTC, toKrause submitted a review, later dismissed

2023-06-15 15:18 UTC, rsteph-de requested changes

2023-06-15 15:18 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/datamodel/metadata/MCRMetadataManager.java
> +            if (mcrObject.getLabel().equals(oldId.toString())) {
check for mcrObject.getLabel() == NULL

2023-06-15 15:42 UTC, rsteph-de approved these changes

2023-06-26 11:31 UTC, merged