MCR-2941 Access commands should be able to read rules from arbitrary ULRs
MyCoRe-Org/mycore pull request #1937
Opened 2023-08-02 15:38 UTC by toKrause

[Link to jira](https://mycore.atlassian.net/browse/MCR-2941).

2023-08-02 16:10 UTC, toKrause commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRAccessCommands.java
> +        return "file://" + new File(filename).getAbsolutePath();
@sonatype-lift ignore

2023-08-08 07:42 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRAccessCommands.java
> +    @MCRCommand(syntax = "update permission {0} for id {1} with rulefile {2} described by {3}",
syntax: ... with **rule**

2023-08-25 12:05 UTC, sebhofmann requested changes

2023-08-25 12:05 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRAccessCommands.java
> +        return "file://" + new File(filename).getAbsolutePath();
I think it would be better to use the method: https://docs.oracle.com/javase/8/docs/api/java/io/File.html#toURI--

2023-08-28 14:36 UTC, sebhofmann approved these changes

2023-08-30 07:20 UTC, merged