MCR-2950 allow null for eTag
MyCoRe-Org/mycore pull request #1943
Opened 2023-08-11 09:12 UTC by rsteph-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-2950).

2023-08-11 15:22 UTC, yagee-de approved these changes

2023-08-11 15:26 UTC, yagee-de requested changes
should be applied to https://github.com/MyCoRe-Org/mycore/tree/2022.06.x

2023-08-11 16:56 UTC, rsteph-de commented
> should be applied to https://github.com/MyCoRe-Org/mycore/tree/2022.06.x

modified base branch

2023-08-15 13:59 UTC, sebhofmann approved these changes

2023-08-15 14:02 UTC, rsteph-de commented
> should be applied to https://github.com/MyCoRe-Org/mycore/tree/2022.06.x

erledigt

2023-08-15 14:33 UTC, merged