MCR-2960 Prevent duplicate common:title and work:contributor-role ele…
MyCoRe-Org/mycore pull request #1956
Opened 2023-08-31 12:17 UTC by chemicus

…ments

[Link to jira](https://mycore.atlassian.net/browse/MCR-).

2023-09-01 08:30 UTC, Possommi requested changes
getting an other but similar error
`Caused by: org.mycore.orcid2.exception.MCRORCIDTransformationException: Transformation failed
	at org.mycore.orcid2.v3.transformer.MCRORCIDWorkTransformerHelper.transformContent(MCRORCIDWorkTransformerHelper.java:82)
	at org.mycore.orcid2.v3.work.MCRORCIDWorkEventHandlerImpl.transformObject(MCRORCIDWorkEventHandlerImpl.java:74)
	at org.mycore.orcid2.v3.work.MCRORCIDWorkEventHandlerImpl.transformObject(MCRORCIDWorkEventHandlerImpl.java:34)
	at org.mycore.orcid2.work.MCRORCIDWorkEventHandler.handlePublication(MCRORCIDWorkEventHandler.java:131)
	at org.mycore.orcid2.work.MCRORCIDWorkEventHandler.handleObjectCreated(MCRORCIDWorkEventHandler.java:79)
	at org.mycore.common.events.MCREventHandlerBase.doHandleEvent(MCREventHandlerBase.java:58)
	at org.mycore.common.events.MCREventManager.handleEvent(MCREventManager.java:152)
	... 65 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 3999; cvc-complex-type.2.4.d: Invalid content was found starting with element 'work:contributor-role'. No child element is expected at this point.
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:204)
	at java.xml/com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:135)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:284)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(XMLSchemaValidator.java:512)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(XMLSchemaValidator.java:3588)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1989)
	at java.xml/com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:830)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2726)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:605)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at java.xml/com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:542)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:889)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:825)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at java.xml/com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1224)
	at java.xml/com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:637)
	at org.jdom2.input.sax.SAXBuilderEngine.build(SAXBuilderEngine.java:217)
	at org.jdom2.input.SAXBuilder.build(SAXBuilder.java:1053)
	at org.mycore.common.xml.MCRXMLParserImpl.parseXML(MCRXMLParserImpl.java:83)
	at org.mycore.orcid2.v3.transformer.MCRORCIDWorkTransformerHelper.transformContent(MCRORCIDWorkTransformerHelper.java:80)
	... 71 more`

2023-09-01 11:01 UTC, Possommi approved these changes

2023-09-04 10:21 UTC, kkrebs approved these changes

2023-09-04 10:23 UTC, kkrebs commented on mycore-orcid2/src/main/resources/xsl/orcid2/v3/mcr2work_generic.xsl
> +  <xsl:template match="mods:mods/mods:titleInfo[@type='translated'][1]">
here we could perhaps prefer english or german or application configured languages instead of first translation, but as bugfix this is ok for me

2023-09-04 10:23 UTC, merged