MCR-2997 add save-xsl to xslt folder
MyCoRe-Org/mycore pull request #1997
Opened 2023-11-10 14:53 UTC by michael-becker

[Link to jira](https://mycore.atlassian.net/browse/MCR-2997)

2023-11-10 17:22 UTC, rsteph-de requested changes
We need to modify the other export command to.
Please look into MCRDerivateCommands and MCRClassification2Commands

2023-11-10 17:22 UTC, rsteph-de commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            " with the stylesheet {2}-object.xsl. For {2}, the default is "+
format code - space before '+')?

2023-11-10 18:30 UTC, rsteph-de commented
I would like do to some additional cleanup in the MCRObjectCommands class.
You could simply remove the class from this Pull-Request and I will update the help text later

2023-11-13 09:04 UTC, michael-becker commented on mycore-base/src/main/java/org/mycore/frontend/cli/MCRObjectCommands.java
> +            " with the stylesheet {2}-object.xsl. For {2}, the default is "+
I removed the file from the commit

2023-11-13 09:06 UTC, michael-becker commented
> I would like do to some additional cleanup in the MCRObjectCommands class. You could simply remove the class from this Pull-Request and I will update the help text later

I removed the file and now only the xsls are in the commit

2023-11-13 09:38 UTC, rsteph-de approved these changes
O.K.

2023-11-13 09:38 UTC, merged