MCR-2647 fix database configuration for JUnit tests
MyCoRe-Org/mycore pull request #2024
Opened 2023-11-30 10:07 UTC by yagee-de

remove hsqldb as a test dependency
minor bug fixes

[Link to jira](https://mycore.atlassian.net/browse/MCR-2647).

2023-11-30 10:19 UTC, rsteph-de requested changes

2023-11-30 10:19 UTC, rsteph-de commented on mycore-base/pom.xml
> +    <dependency>
duplicate entry?

2023-11-30 10:19 UTC, rsteph-de commented on mycore-mods/pom.xml
> +    <dependency>
duplicate dependency?
please check all other pom.xml  too

2023-11-30 10:19 UTC, rsteph-de commented on mycore-packer/src/test/resources/META-INF/persistence.xml
> +      <property name="hibernate.globally_quoted_identifiers" value="true" />
Should these properties be mentioned in the persistence.xml template file for the "real" application?
Are they only for H2 or the other dabase configurations as well?

2023-11-30 13:22 UTC, yagee-de commented on mycore-base/pom.xml
> +    <dependency>
removed it in 3 locations

2023-11-30 13:22 UTC, yagee-de commented on mycore-mods/pom.xml
> +    <dependency>
removed in 3 locations

2023-11-30 13:26 UTC, yagee-de commented on mycore-packer/src/test/resources/META-INF/persistence.xml
> +      <property name="hibernate.globally_quoted_identifiers" value="true" />
In https://github.com/MyCoRe-Org/mycore/blob/40d3deaf86776e84a43756aa1b31db124c4d580e/mycore-base/src/main/resources/configdir.template/resources/META-INF/persistence.xml#L44 another property is used that can be always enabled and MUST be enabled when H2 is used.

2023-11-30 14:04 UTC, rsteph-de commented
We should remove hsqldb settings from `mycore-pi/src/test/resources/META-INF/persistence.xml`
Is the following file still in use or can we delete it: `mycore-base\src\test\resources\META-INF\hibernate.xml`

2023-11-30 18:32 UTC, yagee-de commented
> We should remove hsqldb settings from `mycore-pi/src/test/resources/META-INF/persistence.xml` Is the following file still in use or can we delete it: `mycore-base\src\test\resources\META-INF\hibernate.xml`

done!

2023-12-01 10:36 UTC, sebhofmann approved these changes
I think this is fine. We need to check if this requires a migration for existing tables.

2023-12-05 13:58 UTC, rsteph-de approved these changes
looks good for me

2023-12-05 13:58 UTC, merged