MCR-3043 new text editor
MyCoRe-Org/mycore pull request #2068
Opened 2024-02-19 13:49 UTC by Mewel

[Link to jira](https://mycore.atlassian.net/browse/MCR-3043).

2024-02-20 14:24 UTC, sebhofmann requested changes

2024-02-20 14:24 UTC, sebhofmann commented on mycore-webtools/src/main/vue/texteditor/src/apis/BaseContentHandler.ts
> +        const allow = "HEAD,DELETE,GET,OPTIONS,PUT";
Add a // TODO or use the response.headers.get...

2024-02-20 14:24 UTC, sebhofmann commented on mycore-webtools/src/main/vue/texteditor/package.json
> +    "npm-run-all2": "^6.1.1",
Is npm-run-all2 really required?

2024-02-20 14:24 UTC, sebhofmann commented on mycore-webtools/src/main/vue/texteditor/src/apis/ClassificationsContentHandler.ts
> +    prettifyXml(xml: string) {
I don't like string based xml modification. Can you try https://github.com/riversun/xml-beautify ? It should be easy usable.

2024-02-20 14:24 UTC, sebhofmann commented on mycore-webtools/src/main/vue/texteditor/src/views/TextEditorView.vue
> +  setTimeout(() => {
use nextTick() or even better prevent the ctrl+z browser function by catching the event and return false

2024-02-20 14:48 UTC, Mewel commented on mycore-webtools/src/main/vue/texteditor/src/apis/ClassificationsContentHandler.ts
> +    prettifyXml(xml: string) {
In my opinion the xml from server should be prettified. But this is not supported for classification's yet. So this is more of a workaround for classification's only. I would keep it simple like this, without adding a new dependency.
I will comment it to make it more clear, that this should be removed in the future.

2024-02-20 14:54 UTC, Mewel commented on mycore-webtools/src/main/vue/texteditor/src/views/TextEditorView.vue
> +  setTimeout(() => {
Will use nextTick().
Cannot prevent ctrl+z because I don't know the model state at this point. Ctrl+z should only be prevented if it clears the textarea.

2024-02-22 09:27 UTC, sebhofmann approved these changes

2024-02-22 17:32 UTC, merged