MCR-3053 Redesign API to create configured instances
MyCoRe-Org/mycore pull request #2083
Opened 2024-02-26 18:07 UTC by toKrause

[Link to jira](https://mycore.atlassian.net/browse/MCR-3053).

2024-02-28 17:57 UTC, sebhofmann requested changes

2024-02-28 17:57 UTC, sebhofmann commented on mycore-base/src/main/java/org/mycore/common/config/MCRConfigurableInstanceHelper.java
> +    @SuppressWarnings("unchecked")
This Warning can be removed by changing the Code to:
```
        if (superClass.isInstance(instance)) {
            return Optional.of(superClass.cast(instance));
        } else {
```

Source: https://stackoverflow.com/questions/28921833/why-is-this-an-unchecked-cast-and-how-to-fix-it#answer-28921986

2024-02-28 17:57 UTC, sebhofmann commented on mycore-webtools/src/main/java/org/mycore/webtools/upload/MCRUploadResource.java
> -        Optional<MCRUploadHandler> uploadHandler = MCRConfiguration2
This is still a bad request and not a configuration issue

2024-02-28 18:42 UTC, sebhofmann submitted a review, later dismissed

2024-03-05 17:57 UTC, toKrause commented
Rebased to include current changes of `main`

2024-03-26 13:39 UTC, sebhofmann approved these changes

2024-03-26 13:39 UTC, merged