MCR-3021 Map common:language-code to mods:languageOfCataloging
MyCoRe-Org/mycore pull request #2090
Opened 2024-02-28 12:21 UTC by chemicus

[Link to jira](https://mycore.atlassian.net/browse/MCR-3021).

2024-02-28 12:27 UTC, chemicus commented
The reported error is due to a xsd-validation failure on the transformed orcid work. According to the scheme https://github.com/ORCID/orcid-model/blob/733021de324030e66bed0e4c821dc8cd30a3ef00/src/main/resources/record_3.0/work-3.0.xsd#L96  only one common:language-code is allowed in the scheme. This makes sense, since this field is meant to store the “language used for the metadata” https://github.com/ORCID/orcid-model/blob/733021de324030e66bed0e4c821dc8cd30a3ef00/src/main/resources/record_3.0/work-3.0.xsd#L98 (and not the language of the work/publication itself).
Therefore the correct mapping of common:language-code is mods:recordInfo/mods:languageOfCataloging rather than mods:language

2024-03-26 13:46 UTC, toKrause requested changes

2024-03-26 13:46 UTC, toKrause commented on mycore-orcid2/src/main/resources/xsl/orcid2/v3/work2mcr_generic.xsl
> +          <xsl:value-of select="document(concat('language:',text()))/language/@xmlCode" />
Should check if a corresponding language classification value exists and handle the case when it doesn't.

2024-03-26 13:49 UTC, toKrause commented on mycore-orcid2/src/main/resources/xsl/orcid2/v3/work2mcr_generic.xsl
> +          <xsl:value-of select="document(concat('language:',text()))/language/@xmlCode" />
Should check if a corresponding language classification value exists and handle the case when this is not the case.

2024-03-26 14:03 UTC, kkrebs requested changes
Currently there doesn't seem to be a suitable field for mods:language in ORCID, see https://support.orcid.org/hc/en-us/articles/360006971353-Metadata-in-the-Works-section

That's why we decided to leave it out completely.

2024-05-21 13:33 UTC, kkrebs approved these changes

2024-05-21 13:33 UTC, toKrause approved these changes

2024-05-21 13:33 UTC, merged