MCR-3080 new MCRObjectIDDetector
MyCoRe-Org/mycore pull request #2125
Opened 2024-04-14 09:39 UTC by rsteph-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-3080).

2024-04-18 16:55 UTC, sebhofmann requested changes

2024-04-18 16:55 UTC, sebhofmann commented on mycore-solr/src/main/java/org/mycore/solr/idmapper/MCRSolrIDMapper.java
> +                } catch (Exception e) {
```
                } catch (Exception e) {
                    LOGGER.error("Error retrieving derivate id from SOLR", e);
                }

                if (solrResponse == null) {
                    return result;
                }

                SolrDocumentList solrResults = solrResponse.getResults();
                
                if (solrResults.getNumFound() == 1) {
                   return String.valueOf(solrResults.get(0).getFieldValue("id"));
                }
                if (solrResults.getNumFound() == 0) {
                    LOGGER.info("ERROR: No MyCoRe Derivate ID found for query " + derid);
                }
                if (solrResults.getNumFound() > 1) {
                    LOGGER.info("ERROR: Multiple IDs found for query " + derid);
                }
            
```

2024-04-19 11:01 UTC, rsteph-de commented on mycore-solr/src/main/java/org/mycore/solr/idmapper/MCRSolrIDMapper.java
> +                } catch (Exception e) {
changed as suggested

2024-04-19 11:51 UTC, sebhofmann approved these changes

2024-04-19 14:55 UTC, merged