MCR-3053 fix instantiation of MCROAISolrSetHandler
MyCoRe-Org/mycore pull request #2143
Opened 2024-04-25 09:09 UTC by kkrebs

[Link to jira](https://mycore.atlassian.net/browse/MCR-3053).

2024-04-25 10:36 UTC, toKrause requested changes

2024-04-25 10:36 UTC, toKrause commented on mycore-oai/src/main/java/org/mycore/oai/set/MCROAISolrSetConfiguration.java
> +            .orElseGet(() -> MCRConfiguration2.instantiateClass(getFallbackHandler(configPrefix, setId)));
The fallback handler might be be `null`, support for which was unintentionally dropped in MCR-3053.

Maybe:

```
        MCROAISolrSetHandler handler = MCRConfiguration2
            .getInstanceOf(MCROAISolrSetHandler.class, setConfigPrefix + ".Handler")
            .orElseGet(() -> {
                String fallbackHandler = getFallbackHandler(configPrefix, setId);
                if (fallbackHandler == null) {
                    throw new MCRConfigurationException("Configuration property " +  setConfigPrefix 
                        + ".Handler is not set and no fallback handler could be determined");
                }
                return MCRConfiguration2.instantiateClass(fallbackHandler);
            });
```

2024-04-25 14:10 UTC, rsteph-de commented on mycore-oai/src/main/java/org/mycore/oai/set/MCROAISolrSetConfiguration.java
> +            .orElseGet(() -> MCRConfiguration2.instantiateClass(getFallbackHandler(configPrefix, setId)));
changed as suggested

2024-04-25 14:31 UTC, toKrause approved these changes, later dismissed

2024-04-26 09:58 UTC, sebhofmann commented
The .init method is gone: https://github.com/MyCoRe-Org/mycore/commit/ec5de0a8ec4faf998b7e28ad2ddc7d4f6b7ef36a#diff-63774fe31cf1f8d417b64d01680d7715211199cbb259f3e5699188a4c040b81eL51

2024-04-26 12:37 UTC, kkrebs reviewed
works now with current MIR main

2024-04-29 09:19 UTC, rsteph-de commented
the mix of calls to constructor and init() is a little bit confusing

2024-05-07 12:39 UTC, toKrause approved these changes

2024-05-07 12:40 UTC, merged