MCR-3094 added xpath-based classification mapping
MyCoRe-Org/mycore pull request #2164
Opened 2024-05-23 13:42 UTC by erodde

[Link to jira](https://mycore.atlassian.net/browse/MCR-).

This is still a WIP.

2024-05-27 10:53 UTC, erodde commented
I only tested the feature through unit tests so far, as our applications are not yet compatible to 2023.06.x

2024-05-27 14:47 UTC, erodde commented
Test with local MIR, feature branch and PR https://github.com/MyCoRe-Org/mycore-classifications/pull/17 was successfull, both configured XPath-mappings could be generated (from two different publications matching the respective XPath):

`<mods:classification generator="xpathmapping2orcidWorkType-mycore" authorityURI="http://localhost:8291/mir/classifications/orcidWorkType" valueURI="http://localhost:8291/mir/classifications/orcidWorkType#journal-article"/>`

`<mods:classification generator="xpathmapping2orcidWorkType-mycore" authorityURI="http://localhost:8291/mir/classifications/orcidWorkType" valueURI="http://localhost:8291/mir/classifications/orcidWorkType#online-resource"/>`

Adding an XPath-mapping in an exisiting publication through a repair statement works. Subsequent executions of the EventHandler after making changes in a publication work, mappings are not duplicated. This test only considers the `org.mycore.mods.classification.MCRClassificationMappingEventHandler`.

2024-05-28 07:49 UTC, kkrebs requested changes
Works with MIR and looks good for me. I have just one tiny suggestion for improvement, see my comments.

2024-05-28 07:49 UTC, kkrebs commented on mycore-mods/src/test/resources/MCRClassificationMappingEventHandlerTest/orcidWorkType.xml
> +            <label xml:lang="x-mapping-xpath" text="mods:genre='article' and mods:relatedItem[@type='host']/mods:genre='journal'" />
I think we should use the typical MIR MODS xpath here

2024-05-28 07:49 UTC, kkrebs commented on mycore-mods/src/test/resources/MCRClassificationMappingEventHandlerTest/testMods2.xml
> +    <mods:genre authority="test" displayLabel="test">article</mods:genre>
I think we should use the typical MIR MODS xpath here

2024-05-28 07:49 UTC, kkrebs commented on mycore-mods/src/test/resources/MCRClassificationMappingEventHandlerTest/testMods2.xml
> +        <mods:genre authority="test" displayLabel="test">journal</mods:genre>
I think we should use the typical MIR MODS xpath here

2024-05-30 11:20 UTC, kkrebs approved these changes

2024-06-03 12:03 UTC, fluetze approved these changes

2024-06-10 07:42 UTC, merged