MCR-3126 ocfl filesystem draft
MyCoRe-Org/mycore pull request #2175
Opened 2024-06-10 14:35 UTC by Mewel

[Link to jira](https://mycore.atlassian.net/browse/MCR-3126).

2025-05-09 10:34 UTC, sebhofmann commented
I found a conceptional Problem, which leads to errors in the tiling process. The MCRTreeCopier commits and restarts database transactions. The tiling queue runs in another thread is now able to find the commited tiling jobs and now starts tiling. The ocfl transaction of the Thread in with the MCRTreeCopier did not yet commit its OCFL Transaction, so the files which should be tiled do not exist yet.
We introduced Transaction commits in the MCRTreeCopier, so that in a large upload the connection to the database is released. In my opinion the cleanest aproach would be to remove the transaction restarts from the MCRTreeCopier, to always keep the file transaction and the database transaction in sync and also prevent weird rollback errors.

Meanwhile the uploads happen in another transaction and are stored in a local directory, so the "long" transaction only runs long to upload from the mycore machine to s3, or to copy from one local to another local directory, which should not take that long.

2025-08-01 11:00 UTC, sebhofmann requested changes, later dismissed

2025-08-01 11:00 UTC, sebhofmann commented on mycore-ocfl/src/main/java/org/mycore/ocfl/metadata/MCROCFLXMLMetadataManagerAdapter.java
> +        if (!(ocflRepoProvider instanceof MCROCFLLocalRepositoryProvider localRepositoryProvider)) {
This should still be possible, otherwise the user needs to rebuild the id cache by hand, which is a impossible task with the default layout.

2025-08-04 08:25 UTC, Mewel commented on mycore-ocfl/src/main/java/org/mycore/ocfl/metadata/MCROCFLXMLMetadataManagerAdapter.java
> +        if (!(ocflRepoProvider instanceof MCROCFLLocalRepositoryProvider localRepositoryProvider)) {
I don't think it's a good idea to deactivate this check. I would rather have a migration command which builds the cache. Otherwise the remote repo is not useable anyway.

2025-08-04 08:44 UTC, Mewel commented on mycore-ocfl/src/test/java/org/mycore/ocfl/metadata/migration/MCROCFLCombineIgnoreXPathPrunerTest.java
> +import org.junit.jupiter.api.Test;
This is incorrect.

2025-08-04 10:14 UTC, sebhofmann commented on mycore-ocfl/src/main/java/org/mycore/ocfl/metadata/MCROCFLXMLMetadataManagerAdapter.java
> +        if (!(ocflRepoProvider instanceof MCROCFLLocalRepositoryProvider localRepositoryProvider)) {
There is a command which builds the cache, but it uses this method. The method should not be called anywhere, except in the command. All other places should use the cache or the database.

2025-08-04 10:25 UTC, Mewel commented on mycore-ocfl/src/main/java/org/mycore/ocfl/metadata/MCROCFLXMLMetadataManagerAdapter.java
> +        if (!(ocflRepoProvider instanceof MCROCFLLocalRepositoryProvider localRepositoryProvider)) {
Lets talk about this tomorrow, cause this method works directly with the Path API. It wants to call getRepositoryRoot(). This is not available on a remote S3 repository. There is no root path.

So either this method is wrongly implemented and shouldn't work with Path's or you would need to migrate to the MCRFileBaseCacheObjectIDGenerator first in order to use OCFL S3 repos.

2025-08-27 12:03 UTC, toKrause commented on mycore-ocfl/src/main/java/org/mycore/ocfl/repository/MCROCFLRepositoryProvider.java
> +    static MCROCFLRepositoryProvider getProvider(String id) {
Name `obtainInstance` would be more in line with the rest of MyCoRe.

2025-08-27 12:03 UTC, toKrause commented on mycore-ocfl/pom.xml
> +      <groupId>software.amazon.awssdk</groupId>
Presumably, the dependencies for S3-support could be marked as optional. 

Not everyone who wishes to use OCFL is going to also use S3. Theese dependecies could therefore be keept off the classpath for, presumably, a lot of users.

As far as I  can see, S3-supoport is implementes soley in `MCROCFLS3RepositoryProvider`.
Have you consideres moving S3-support into a separate module `mycore-ocfl-s3` that contains only that class, the corresponding entries in `mycore.properties` and the corresponding dependencies in `pom.xml`.

Not a "must", but would be nice.

2025-08-27 14:29 UTC, toKrause submitted a review, later dismissed

2025-08-27 16:32 UTC, merged