MCR-3115 allow parallel indexing in different cores
MyCoRe-Org/mycore pull request #2179
Opened 2024-06-12 14:00 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-3115).

based on https://github.com/MyCoRe-Org/mycore/pull/2167

change base to main if https://github.com/MyCoRe-Org/mycore/pull/2167 is merged

2024-07-02 11:02 UTC, toKrause requested changes
Only some minor stuff.

2024-07-02 11:02 UTC, toKrause commented on mycore-solr/src/main/java/org/mycore/solr/MCRSolrCore.java
> +    public MCRSolrCore(String serverURL, String name, String configSet, Integer shardCount, Set<MCRSolrCoreType> type) {
Last parameter should be names `types`

2024-07-02 11:02 UTC, toKrause commented on mycore-solr/src/main/java/org/mycore/solr/MCRSolrCore.java
> +    protected void setup(String serverURL, String name, String configSet,
Last parameter should be names `types`

2024-07-02 11:02 UTC, toKrause commented on mycore-solr/src/main/java/org/mycore/solr/index/MCRSolrIndexEventHandler.java
> +            final List<MCRSolrCore> mainSolrClient = MCRSolrCoreManager.getCoresForType(MCRSolrCoreType.MAIN);
`mainSolrClient` should be renamed to, maybe `mainSolrCores`

2024-07-02 11:02 UTC, toKrause commented on mycore-solr/src/main/java/org/mycore/solr/index/MCRSolrIndexer.java
> +    public static void rebuildMetadataIndex(List<MCRSolrCore> solrCore) {
Should be `solrCores`

2024-07-02 11:02 UTC, toKrause commented on mycore-solr/src/main/java/org/mycore/solr/index/handlers/stream/MCRSolrFilesIndexHandler.java
> +        if (!docs.isEmpty()) { // TODO: check this crap
Could use a better description of what exactly needs to be done here

2024-07-05 08:10 UTC, toKrause approved these changes, later dismissed

2024-07-16 12:53 UTC, rsteph-de approved these changes
looks good for me

2024-07-16 12:53 UTC, merged