MCR-3149 replace ckeditor with tinymce
MyCoRe-Org/mycore pull request #2209
Opened 2024-07-23 15:10 UTC by Mewel

[Link to jira](https://mycore.atlassian.net/browse/MCR-3149).

2024-07-30 12:44 UTC, sebhofmann requested changes

2024-07-30 12:44 UTC, sebhofmann commented on mycore-wcms2/GruntFile.js
> +                            cwd: './node_modules/tinymce-i18n/langs7',
This seems to be wrong `/langs7',`

2024-08-12 11:38 UTC, Mewel commented on mycore-wcms2/GruntFile.js
> +                            cwd: './node_modules/tinymce-i18n/langs7',
This is actually correct. It refers to the tinyMCE version 7.

2024-08-15 12:10 UTC, sebhofmann approved these changes
I tested it and it works.

2024-08-15 12:14 UTC, merged