MCR 3189 fix pmd issues in mycore solr
MyCoRe-Org/mycore pull request #2258
Opened 2024-09-12 14:21 UTC by Antoniafriedrich

[Link to jira](https://mycore.atlassian.net/browse/MCR-3189).

2024-09-19 16:08 UTC, rsteph-de commented on mycore-solr/src/main/java/org/mycore/solr/search/MCRSolrSearchUtils.java
> +            Objects.requireNonNull(action);
will never fail after `if(action == null) throws`

2024-09-19 16:10 UTC, rsteph-de commented on mycore-solr/src/main/java/org/mycore/solr/index/handlers/content/MCRSolrMCRContentMapIndexHandler.java
> +                } catch (SolrServerException|IOException e) {
format code (space before+after `|`) ?

2024-09-19 16:16 UTC, rsteph-de commented on mycore-solr/src/main/java/org/mycore/solr/index/handlers/content/MCRSolrMCRContentMapIndexHandler.java
> +        }  finally {
format code - 2 spaces?

2024-09-19 16:19 UTC, rsteph-de requested changes
some minor issues, otherwise O.K.

2024-09-24 12:59 UTC, toKrause approved these changes

2024-10-08 13:06 UTC, merged