MCR 3193 fix pmd issues in mycore mets
MyCoRe-Org/mycore pull request #2259
Opened 2024-09-13 08:36 UTC by Antoniafriedrich

[Link to jira](https://mycore.atlassian.net/browse/MCR-3193).

2024-09-24 13:07 UTC, sebhofmann requested changes
Some minor issues. Rest looks good.

2024-09-24 13:07 UTC, sebhofmann commented on mycore-mets/src/main/java/org/mycore/mets/model/converter/MCRAltoLinkTypeAdapter.java
> +                default -> throw new JsonParseException(name + " not recognized");
previously unknown names were just ignored.

2024-09-24 13:07 UTC, sebhofmann commented on mycore-mets/src/main/java/org/mycore/mets/model/converter/MCRMetsLinkTypeAdapter.java
> +                default -> throw new JsonParseException(name + " is not a valid link type");
previously unknown names were just ignored.

2024-10-08 13:13 UTC, rsteph-de commented on mycore-mets/src/main/java/org/mycore/mets/model/converter/MCRAltoLinkTypeAdapter.java
> -                case "end" -> end = jsonReader.nextString();
We want to keep the switch and add a default branch

2024-10-08 13:13 UTC, rsteph-de commented on mycore-mets/src/main/java/org/mycore/mets/model/converter/MCRMetsLinkTypeAdapter.java
> -                case "to" -> ml.setToString(jsonReader.nextString());
We want to keep the switch and add a default branch

2024-10-15 09:04 UTC, rsteph-de commented
2024-10-15T07:13:53.4502745Z 07:13:53,449 [INFO] There are 3 errors reported by Checkstyle 10.12.7 with /home/runner/work/mycore/mycore/checkstyle.xml ruleset.
2024-10-15T07:13:53.4527722Z 07:13:53,451 [ERROR] src/main/java/org/mycore/mets/model/converter/MCRAltoLinkTypeAdapter.java:[55,43] (coding) InnerAssignment: Inner assignments should be avoided.
2024-10-15T07:13:53.4531927Z 07:13:53,451 [ERROR] src/main/java/org/mycore/mets/model/converter/MCRAltoLinkTypeAdapter.java:[56,39] (coding) InnerAssignment: Inner assignments should be avoided.
2024-10-15T07:13:53.4536340Z 07:13:53,451 [ERROR] src/main/java/org/mycore/mets/model/converter/MCRAltoLinkTypeAdapter.java:[57,35] (coding) InnerAssignment: Inner assignments should be avoided.

2024-10-15 11:29 UTC, rsteph-de commented on mycore-mets/src/main/java/org/mycore/mets/model/converter/MCRAltoLinkTypeAdapter.java
> -            //CSOFF: InnerAssignment
the 2 comments need to be added to disable checkstyle here

2024-10-15 11:54 UTC, rsteph-de approved these changes
Looks good for me now

2024-10-15 12:40 UTC, merged