MCR-3194  prepare orcid authentication for guests
MyCoRe-Org/mycore pull request #2260
Opened 2024-09-13 08:54 UTC by golsch

[Link to jira](https://mycore.atlassian.net/browse/MCR-).

2024-09-24 13:05 UTC, kkrebs submitted a review, later dismissed
looks good for me, please add some documentation

2024-09-25 13:54 UTC, golsch commented
> looks good for me, please add some documentation

I have added documentation to the README.md and also created a PR for the website: https://github.com/MyCoRe-Org/mycore-website/pull/74

2024-09-26 06:51 UTC, chemicus requested changes

2024-09-26 06:51 UTC, chemicus commented on mycore-orcid2/src/main/java/org/mycore/orcid2/oauth/resources/MCRORCIDOAuthResource.java
> +            }
Minor remark: The two if-statements can be merged into one

2024-09-26 07:56 UTC, chemicus approved these changes

2024-09-26 09:15 UTC, merged