MCR-3176 fix pmd issues in mycore-iview2
MyCoRe-Org/mycore pull request #2277
Opened 2024-09-27 13:26 UTC by yagee-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-3176).

Should replace https://github.com/MyCoRe-Org/mycore/pull/2245

2024-09-30 11:50 UTC, Antoniafriedrich commented on mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java
> +        MCRIIIFImageSourceRegion sourceTiles = new MCRIIIFImageSourceRegion(
Why was the formula for the sourceTiles changed?

2024-09-30 11:50 UTC, Antoniafriedrich commented on mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java
> +        int xt = (int) ((targetSize.width() - 1) / 2);
Casting xt and yt to 'int' is redundant.

2024-10-07 09:35 UTC, Mewel requested changes

2024-10-07 09:35 UTC, Mewel commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRIView2Commands.java
>              try (DirectoryStream<Path> directoryStream = Files.newDirectoryStream(file)) {
boolean isEmptyDirectory = Files.list(file).findAny().isEmpty()
is much shorter than using a directory stream

2024-10-08 10:51 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java
> +        int xt = (int) ((targetSize.width() - 1) / 2);
Yep, good point the final type requested is also a double, so this makes no sense at all.

2024-10-08 11:46 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRIView2Commands.java
>              try (DirectoryStream<Path> directoryStream = Files.newDirectoryStream(file)) {
Thanks, implemented in https://github.com/MyCoRe-Org/mycore/pull/2277/commits/3f0661ad939505ff717d05573fbf415811fe67e5

2024-10-22 11:51 UTC, Mewel approved these changes

2024-10-22 12:08 UTC, merged