MCR-3304 neo4j raises exception if the server url is not defined
MyCoRe-Org/mycore pull request #2332
Opened 2024-11-22 16:21 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-3304).

2024-11-27 10:14 UTC, michael-becker requested changes

2024-11-27 10:14 UTC, michael-becker commented on mycore-neo4j/src/main/java/org/mycore/mcr/neo4j/index/MCRNeo4JIndexEventHandler.java
> +            LOGGER.info("Neo4J Indexing is disabled");
maybe add: because the property MCRNeo4JConstants.DEFAULT_NEO4J_SERVER_URL ist not set

2024-12-02 10:27 UTC, golsch commented
Why not simply make the event handler optional? This way, you are also open to adaptations if necessary.

2024-12-05 16:48 UTC, kkrebs approved these changes

2024-12-05 16:50 UTC, merged