MCR-3227 enable PMD rule GuardLogStatement
MyCoRe-Org/mycore pull request #2349
Opened 2024-12-20 14:19 UTC by yagee-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-3227).

2025-01-02 11:55 UTC, Mewel requested changes

2025-01-02 11:55 UTC, Mewel commented on mycore-base/src/main/java/org/mycore/access/MCRAccessBaseImpl.java
> + *
You have a blank line at the end of each javadoc comment. Looks strange.

Also in between the javadoc you added some. Intellij doesn't like it: "Blank line will be ignored -> Insert &lt;p&gt;."

2025-01-02 11:55 UTC, Mewel commented on mycore-base/src/main/java/org/mycore/common/MCRMailer.java
> +     *
One line break should be enough

2025-01-06 13:27 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/access/MCRAccessBaseImpl.java
> + *
Comes from IntelliJ. It automatically removes blanks at end of line on save. Do not know how to deactivate it, but those "space" are not needed. That's why I didn't put much effort in it.

2025-01-14 13:12 UTC, Mewel approved these changes

2025-01-16 11:25 UTC, merged