MCR-1578 allow mods related item usage also for non mods object types
MyCoRe-Org/mycore pull request #238
Opened 2017-05-08 08:30 UTC by paschty

2017-05-08 11:54 UTC, yagee-de requested changes

2017-05-08 11:54 UTC, yagee-de commented on mycore-mods/src/main/java/org/mycore/mods/MCRMODSMetadataShareAgent.java
> +            if (MCRMODSWrapper.isSupported(recipientId)) {
LOGGER should go inside the 'isSupported' block

2017-05-09 08:31 UTC, kkrebs approved these changes

2017-05-15 13:05 UTC, yagee-de approved these changes

2017-05-15 13:40 UTC, merged