issues/MCR-1398-Exception added catchEx uri resolver
MyCoRe-Org/mycore pull request #24
Opened 2016-10-18 10:08 UTC by paschty

added a catchEx URI resolver which produces xml in error case like:
<exception>
<message>$message</message>
<stacktrace>$printStackTraceOutput</stracktrace>
</exception>

2016-10-18 10:10 UTC, paschty commented
Please resolve https://mycore.atlassian.net/browse/MCR-1398 on merge.

2016-10-18 10:11 UTC, yagee-de commented
Please fix commit message and open pull request against LTS branch

2016-10-18 10:13 UTC, yagee-de requested changes

2016-10-18 10:13 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/common/xml/MCRURIResolver.java
> -
Keep old order of imports and change only what is necessary

2016-10-18 11:44 UTC, paschty commented
Formatting should be fine now..

2016-10-19 07:19 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/common/xml/MCRURIResolver.java
> +                Element stacktraceElement = new Element("stacktrace");
I think that the `<stacktrace>` element should have an attribute `xml:space="preserve"`. See [definition of xml:space](https://www.w3.org/TR/xml/#sec-white-space).

2016-10-20 08:41 UTC, yagee-de approved these changes

2016-10-20 08:41 UTC, merged