MCR-1408 add redirect to MCRBasketServlet
MyCoRe-Org/mycore pull request #26
Opened 2016-10-19 13:29 UTC by eckstueck

- added possibility to send a URL as redirect parameter to MCRBasketServlet

2016-10-19 14:13 UTC, yagee-de requested changes

2016-10-19 14:13 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/frontend/basket/MCRBasketServlet.java
> +                res.sendRedirect(res.encodeRedirectURL(redirect));
If a referrer is given but the redirect parameter is empty. What happens?
If the redirect parameter is given but no referrer is available. What happens?

2016-10-20 08:10 UTC, eckstueck commented
squashed all commits to a single commit
:shipit: ?

2016-10-20 08:40 UTC, yagee-de approved these changes

2016-10-20 08:40 UTC, merged