MCR-1597 refactored MCRGoogleSitemap
MyCoRe-Org/mycore pull request #264
Opened 2017-05-31 09:26 UTC by KelKx

use Solr instead of MetadataStore.use property MCR.GoogleSitemap.SolrQuery to define Solr query.
default query delivers only published and stateless MODSObjects

2017-06-13 11:58 UTC, yagee-de requested changes

2017-06-13 11:58 UTC, yagee-de commented on .travis.yml
> +  - mkdir ${HOME}/tmp
please remove this change. Has nothing to do with the ticket

2017-06-13 11:58 UTC, yagee-de commented on mycore-base/src/main/resources/config/mycore.properties
> +  MCR.GoogleSitemap.SolrQuery=(objectType:mods AND -state:*) OR (objectType:mods AND state:published)
Why is that in mycore-base? mycore-base does not know anything about SOLR or site maps or even MODS.

2017-06-13 16:30 UTC, kkrebs commented on mycore-base/src/main/resources/deprecated.properties
>  MCR.googlesitemap.freq=MCR.GoogleSitemap.Freq
you have to write the new property name behind the old one
MCR.GoogleSitemap.Types=MCR.GoogleSitemap.SolrQuery

2017-06-13 16:31 UTC, kkrebs commented on mycore-indexing/src/main/resources/components/indexing/config/mycore.properties
> +# Sets the filter for the Solr query
, list all mycore objects is default

2017-06-14 11:46 UTC, kkrebs approved these changes

2017-06-14 11:46 UTC, merged