MCR-1627 Implemented RSS Feed Importer
MyCoRe-Org/mycore pull request #271
Opened 2017-06-08 14:05 UTC by fluetze

2017-06-14 13:46 UTC, sebhofmann requested changes

2017-06-14 13:46 UTC, paschty commented on mycore-mods/pom.xml
> +<?xml version="1.0" encoding="UTF-8"?>
The indent seems to wrong or maybe the line ending ?

2017-06-14 13:46 UTC, paschty commented on pom.xml
> +        <version>1.5.1</version>
rome version 1.5.1 is to old and uses JDOM(1).
(https://github.com/rometools/rome/blob/v1.5.1/pom.xml)
You should switch to at least 1.6.0 which is using jdom2

2017-06-14 13:46 UTC, paschty commented on mycore-mods/src/main/java/org/mycore/mods/MCRMODSCommands.java
> +/*
same like in pom.xml

2017-06-14 13:46 UTC, paschty commented on mycore-mods/src/main/java/org/mycore/mods/rss/MCRRSSFeedImporter.java
> +    private static final String PROPERTY_MAIL_ADDRESS = "MCR.Mail.Address";
MCR.Mail.Recipients is better here, but not sure.

2017-06-19 08:00 UTC, fluetze commented
Code is a mess, withdraw this pull request

2017-06-19 08:00 UTC, closed without merging