MCR-1762 filter for Rest-API output
MyCoRe-Org/mycore pull request #478
Opened 2018-01-03 12:43 UTC by OPNA2608

Bitte schaut mal, ob das okay ist.
Danke.

2018-01-03 14:08 UTC, yagee-de requested changes

2018-01-03 14:08 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +        String xslfile = MCRConfiguration.instance().getString("MCR.RestAPI.v1.Filter.XML", "");
Please use [MCRContentTransformerFactory](http://www.mycore.de/generated/mycore-2017.06.0/mycore-base/apidocs/org/mycore/common/content/transformer/MCRContentTransformerFactory.html) to do transformations for better performance and more flexibility

2018-01-03 14:08 UTC, yagee-de commented on mycore-restapi/src/main/resources/components/restapi/config/mycore.properties
> +# MCR.RestAPI.v1.Filter.XML=xsl/mycoreobject-xml.xsl
`MCR.RestAPI.v1.Filter.XML=mycoreobject-xml` would use the mycoreobject-xml Content-Transformer (if defined)

2018-01-04 15:02 UTC, yagee-de requested changes

2018-01-04 15:02 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +            if (MCRConfiguration.instance().getString("MCR.ContentTransformer.RestApiXmlFilter.Stylesheet", "").length() > 0) {
Do not hardcode any transformer configuration here. It's better to make a filter property that defines a ContentTransformer like in my original review.
Simply add something like `MCR.RestAPI.v1.Filter.XML=RestApiXmlFilter` and use only `MCR.RestAPI.v1.Filter.XML` in your code to detect IF there is a content transformer defined.
ContentTransfomer MAY use Stylesheets but can be of any kind...

2018-01-04 15:02 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +                MCRContentTransformer trans = MCRContentTransformerFactory.getTransformer("RestApiXmlFilter");
use the value of `MCR.RestAPI.v1.Filter.XML` here and do not hard code a specific transformer here

2018-01-05 10:03 UTC, yagee-de approved these changes

2018-01-08 08:38 UTC, kkrebs approved these changes

2018-01-16 10:06 UTC, merged