MCR-1783 Remove whitespace after classname properties
MyCoRe-Org/mycore pull request #484
Opened 2018-01-16 14:27 UTC by bt1cu

Add new methods getClassOf to get classes via configuration properties and integrate it in methods of getInstnceOf . Replace class calls in used classes.

2018-01-18 07:48 UTC, kkrebs approved these changes

2018-01-18 08:22 UTC, yagee-de requested changes

2018-01-18 08:22 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/common/config/MCRConfiguration.java
> +    public Class<?> getClassOf(String name, String defaultname) throws MCRConfigurationException {
the default value should be a Class object like getLong, getBoolean, etc.

2018-01-18 08:26 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/common/config/MCRConfiguration.java
> +    public Class<?> getClassOf(String name, String defaultname) throws MCRConfigurationException {
maybe naming should also be changed to getClass instead of getClassOf

2018-01-25 10:18 UTC, yagee-de commented
Will be moved to master

2018-01-25 10:18 UTC, closed without merging