MCR-1807 fixed session handling
MyCoRe-Org/mycore pull request #517
Opened 2018-02-26 15:15 UTC by paschty

* MCRSessionManager can now lock a thread. So no session can be created.
* Use mycore default jersey configuration in RESTAPI
* Created filter which can lock session creation
* Use filter when MCRStatic is annotated
* Removed MCRStatic from RESTAPI because it uses it uses sessions

2018-02-26 17:28 UTC, rsteph-de reviewed
MCRSessionMgr.lock() and unlock()
increase the complexity of MCR session handling

2018-02-27 11:32 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/MCRRESTResourceConfig.java
> +        String propertyString = MCRConfiguration.instance().getString("MCR.RestAPI.Resource.Packages");
use getStrings() here

2018-02-27 11:33 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/feature/MCRRESTFeature.java
> +        String propertyString = MCRConfiguration.instance().getString(MCRRESTResourceConfig.REST_API_PACKAGE);
use getStrings() here

2018-02-27 11:34 UTC, yagee-de requested changes
two minor changes requested. Rest looks OK to me.

2018-02-27 13:59 UTC, Mewel approved these changes
works with jportal

2018-02-28 18:15 UTC, kkrebs requested changes
Tested in MIR. There is still one session type staying open.

2018-03-21 14:42 UTC, yagee-de approved these changes

2018-03-23 12:58 UTC, kkrebs approved these changes

2018-03-23 16:06 UTC, merged