MCR-1817 add access links to derivates
MyCoRe-Org/mycore pull request #526
Opened 2018-03-09 15:15 UTC by eckstueck

added access links to derivates

2018-04-12 05:55 UTC, yagee-de requested changes

2018-04-12 05:55 UTC, yagee-de commented on mycore-mods/src/main/resources/xsl/mods-enhancer.xsl
> +        <xsl:copy-of select="document(concat('xslStyle:mcr_directory-recursive:ifs:',@xlink:href,'/'))" />
depends on XSL from mir-module, should be included in mycore

2018-04-12 13:54 UTC, eckstueck commented
added mcr_directory-recursive.xsl to mycore

2018-05-16 10:15 UTC, kkrebs approved these changes

2018-05-25 06:27 UTC, yagee-de approved these changes

2018-05-25 06:28 UTC, merged