MCR-1807 fixed rest api sessions
MyCoRe-Org/mycore pull request #575
Opened 2018-05-08 16:01 UTC by paschty

[Link to jira](https://mycore.atlassian.net/browse/MCR-1807).

2018-05-08 20:07 UTC, kkrebs requested changes
get following warning:

[WARNING] [talledLocalContainer] WARNUNG: unavailable
[INFO] [talledLocalContainer] javax.servlet.ServletException: Resource configuration class org.mycore.restapi.MCRRESTResourceConfig is not a subclass of class javax.ws.rs.core.Application.

2018-05-09 04:45 UTC, yagee-de commented
MCR-1807 is marked for 2017.06.0.x branch, please change

2018-05-15 19:46 UTC, kkrebs approved these changes

2018-05-16 09:11 UTC, rsteph-de approved these changes
tested and works !!!

2018-05-16 12:25 UTC, merged