Issues/mcr 1826 modular solr schema definition
MyCoRe-Org/mycore pull request #602
Opened 2018-06-01 08:48 UTC by bt1cu

The build of SOLR definitions via MyCoRe commands should work. For MODS a first implementation of SOLR definition is in mycore-mods. Base definitions are in mycore-base. It use the core template under  https://github.com/MyCoRe-Org/mycore-default-core-template .
See the feature description under mycore.de -> documentation -> SOLR7 and Search

2018-06-08 13:44 UTC, sebhofmann requested changes
We should maybe consider to refactor everything related to serverURL. If we would use coreURL the code would be easier to understand at some places. 
The MCRSolrClientFactory overwrites the cores if they have the same name.
If i had a Solr-Server which stores all classifications and a Solr-Server which stores all mycore-objects and some applications, then i would like to name the cores just like the application name. e.g.
http://classification-solr.de/solr/mir and http://object-solr.de/solr/mir in my MyCoRe the MCRSolrClientFactory would just know one core. This example seems quite a strech but it shows a weakness of the current design.

I think we should define cores like MCR.Some.Prefix.{coreID}=http://the-url.de/solr/{coreName}
The coreName should not nessesary have to be the coreId. The coreName should not matter to MyCoRe at all.

2018-06-08 13:44 UTC, sebhofmann commented on mycore-solr/src/main/java/org/mycore/solr/MCRSolrClientFactory.java
> +    public static SolrClient getSolrDefaultClient() {
If we change the API here (method name) we should also make this method return optional because getDefaultSolrCore can reuturn null and produce a NPE

2018-06-08 13:44 UTC, sebhofmann commented on mycore-solr/src/main/java/org/mycore/solr/MCRSolrClientFactory.java
> +    public static SolrClient getConcurrentSolrDefaultClient() {
Same as in line 100

2018-06-08 13:44 UTC, paschty commented on mycore-solr/src/main/java/org/mycore/solr/MCRSolrClientFactory.java
> +    public static void setSolrClient(String serverURL, String core) {
This method should be renamed to  something like add or addCore. The name setSolrClient indicates there is only one solr client in this Factory and you overwrite it, but it its only a shorthand to add a new solr core.

2018-06-20 10:46 UTC, sebhofmann approved these changes

2018-06-26 11:28 UTC, kkrebs approved these changes

2018-06-26 12:16 UTC, merged