Issues/mcr 1922 read solr config from classpath
MyCoRe-Org/mycore pull request #662
Opened 2018-08-09 15:41 UTC by rsteph-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-1922).

2018-08-10 05:42 UTC, yagee-de requested changes

2018-08-10 05:42 UTC, yagee-de commented on mycore-base/src/main/java/org/mycore/common/config/MCRConfigurationInputStream.java
> +        InputStream configStream = getConfigFileStream(filename);
use try-with-resource to close the InputStream or it will leak

2018-08-16 06:31 UTC, bt1cu commented
it should be okay

2018-08-16 06:32 UTC, bt1cu approved these changes
is okay

2018-08-17 07:28 UTC, yagee-de approved these changes

2018-08-17 07:29 UTC, merged