MCR-2003 fix xsd
MyCoRe-Org/mycore pull request #799
Opened 2019-04-12 09:11 UTC by paschty

[Link to jira](https://mycore.atlassian.net/browse/MCR-2003).

2019-04-12 09:14 UTC, fluetze approved these changes

2019-04-25 12:54 UTC, rochpaul commented
Tested with a new MIR Installation
mir[mir-master] + mycore[issues/MCR-2003-fix_xsd]


Testing steps

1) Dissertation creation with uploading file

- Login with user in author role
- Create new Dissertation
- Upload file

-----------------------------------

- \mir\data\metadata\mir\mods\0000\00\mir_mods_00000001.xml was created in filesystem
- \mir\data\metadata\mir\derivate\0000\00\mir_derivate_00000001.xml was created in filesystem

-----------------------------------


2) Remove uploaded file (as administrator in standard mir installation)
- Lock on \mir\data\metadata\mir\derivate\0000\00\ directory
- removed derivate dependency exists furthermore in \mir\data\metadata\mir\mods\0000\00\mir_mods_00000001.xml

 <structure>
    <derobjects class="MCRMetaDerivateLinkID">
      <derobject inherited="0" xlink:type="locator" xlink:title="data object from mir_mods_00000001" xlink:label="default" xlink:href="mir_derivate_00000001" mainDoc="Vorlage_2018-11-14.pptx" />
    </derobjects>
  </structure>

- Frontend shows  404 Not Found (See Screenshot MCR-2003-remove-uploaded-file)
![MCR-2003-remove-uploaded-file](https://user-images.githubusercontent.com/17741388/56737046-d8eabc00-6769-11e9-846e-7ddb1417f236.PNG)


- Inconsistent state after webapp shutdown
- The derivate is removed but the derivate dependency exists furthermore

2019-04-25 13:05 UTC, rochpaul commented
stacktrace for removing derivate mir_derivate_00000002 in document mir_mods_00000002

[stacktrace_test_removement_mir_derivate_00000002.txt](https://github.com/MyCoRe-Org/mycore/files/3116950/stacktrace_test_removement_mir_derivate_00000002.txt)

2019-04-30 09:53 UTC, kkrebs requested changes
work in progress, some more testing needed

2019-05-02 13:18 UTC, kkrebs commented on mycore-base/src/main/java/org/mycore/datamodel/metadata/MCRMetadataManager.java
> +        final MCRMetaDerivateLinkID der = MCRMetaDerivateLinkIDFactory.getInstance().getDerivateLink(mcrDerivate);
this has changed from link to derobject, we need:
-> better documentation
-> better naming

2019-05-02 13:28 UTC, kkrebs commented on mycore-migration/src/main/java/org/mycore/migration/cli/MCRMigrationCommands.java
> +    @MCRCommand(syntax = "migrate MCR-2003 for object {0}")
we should not use ticket number here

2019-05-02 13:29 UTC, kkrebs commented on mycore-migration/src/main/java/org/mycore/migration/cli/MCRMigrationCommands.java
> +    @MCRCommand(syntax = "migrate MCR-2003 set order of Derivate {0} to {1}")
"Derivate" -> "derivate"

2019-05-02 13:43 UTC, kkrebs commented on mycore-base/src/main/java/org/mycore/datamodel/metadata/MCRDefaultMetaDerivateLinkIDFactory.java
> +    public MCRMetaDerivateLinkID getDerivateLink(MCRDerivate der) {
we should think about naming here
 - MCRMetaStructureDerObject
 - MCRMetaDerObject

2019-05-08 16:06 UTC, kkrebs approved these changes

2019-05-08 16:08 UTC, merged