MCR-2090 add support for IIIF to viewer
MyCoRe-Org/mycore pull request #843
Opened 2019-08-16 15:38 UTC by eckstueck

first version of IIIF support

you can use IIIF by adding iiif to the path (viewer/iiif/{derivateID}/)

[Link to jira](https://mycore.atlassian.net/browse/MCR-2090).

2019-08-16 15:40 UTC, eckstueck commented
Do not merge yet!
Code need some clean up.
Alto support with iiif needs to be added again.
Support for external iiif manifests need to be added.

2019-08-21 12:39 UTC, kkrebs commented
please rebase to branch 2019.06.x

2019-09-12 07:44 UTC, sebhofmann requested changes

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/java/org/mycore/viewer/configuration/MCRViewerIIIFConfiguration.java
> +        setProperty("manifestURL", MCRFrontendUtil.getBaseURL() + "rsc/iiif/presentation/mets/" + derivate + "/manifest");
It would be good if can configure this.

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/java/org/mycore/viewer/configuration/MCRViewerIIIFConfiguration.java
> +        addLocalScript("lib/manifesto/manifesto.js", true, isDebugMode(request));
debugParameterSet can be passed here

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/components/MyCoReIIIFComponent.ts
> +namespace mycore.viewer.components {
This class should share share code with MyCoReMetsComponent.

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/components/MyCoReIIIFPageProviderComponent.ts
> +    export class MyCoReIIIFPageProviderComponent extends ViewerComponent {
Same as MyCoReIIIFComponent

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/components/events/IIIFLoadedEvent.ts
> +    export class MetsLoadedEvent extends MyCoReImageViewerEvent {
This Class is not necessary for iiif

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/components/events/RequestAltoModelEvent.ts
> +    export class RequestAltoModelEvent extends MyCoReImageViewerEvent {
See same as MyCoReIIIFComponent

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/widgets/IIIFStructureBuilder.ts
> +namespace mycore.viewer.widgets.iiif {
Most content of this Class can be removed.

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/widgets/TileImagePageIIIF.ts
> +    export class TileImagePageIIIF implements model.AbstractPage {
This and  TileImagePage also have almost the same code.

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/widgets/alto/AltoChange.ts
> +    export interface AltoChangeSet {
Not needed in IIIF

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/widgets/alto/AltoEditorWidget.ts
> +    export class AltoEditorWidget {
Not needed in IIIF

2019-09-12 07:44 UTC, paschty commented on mycore-viewer/src/main/typescript/modules/iiif/widgets/modal/ViewerPrintModalWindow.ts
> +    export class ViewerPrintModalWindow extends IviewModalWindow {
Not needed in IIIF

2019-09-16 12:14 UTC, eckstueck commented
Please review code again. I merged some classes an changed original code.

2019-09-18 09:25 UTC, eckstueck commented
All reasonable codacy issues should now be fixed.

2019-09-18 16:29 UTC, sebhofmann approved these changes

2019-09-18 16:34 UTC, merged