MCR-2159 separated methods to retrieve MCRObjectIDs from pathParams
MyCoRe-Org/mycore pull request #921
Opened 2020-03-05 17:33 UTC by rsteph-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-2159).

2020-03-05 17:37 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212&bid=16856521)

2020-03-05 17:37 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static MCRObjectID retrieveMCRObjectID(String idString) throws MCRRestAPIException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid reassigning parameters such as 'idString'](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 17:37 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static MCRObjectID retrieveMCRDerivateID(MCRObjectID parentObjId, String derIDString)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid reassigning parameters such as 'derIDString'](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 17:37 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static Response listDerivates(UriInfo info, String mcrId, String format,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid really long methods.](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 17:37 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +            if (!derKey.equals("mcr") && !derKey.equals("label") && !derKey.equals("classification")) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Position literals first in String comparisons](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 17:37 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static MCRObjectID retrieveMCRDerivateID(MCRObjectID parentObjId, String derIDString)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'retrieveMCRDerivateID(MCRObjectID, String)' has an NPath complexity of 8100](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 17:37 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static Response listDerivates(UriInfo info, String mcrId, String format,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'listDerivates(UriInfo, String, String, String)' has an NPath complexity of 3240](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:11 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 6
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212&bid=16856521)

2020-03-05 18:11 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static MCRObjectID retrieveMCRObjectID(String idString) throws MCRRestAPIException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid reassigning parameters such as 'idString'](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:11 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static Response listDerivates(UriInfo info, String mcrId, String format,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'listDerivates(UriInfo, String, String, String)' has an NPath complexity of 3240](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:11 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static MCRObjectID retrieveMCRDerivateID(MCRObjectID parentObjId, String derIDString)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'retrieveMCRDerivateID(MCRObjectID, String)' has an NPath complexity of 8100](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:11 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static Response listDerivates(UriInfo info, String mcrId, String format,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid really long methods.](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:11 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static MCRObjectID retrieveMCRDerivateID(MCRObjectID parentObjId, String derIDString)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid reassigning parameters such as 'derIDString'](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:11 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +            if (!derKey.equals("mcr") && !derKey.equals("label") && !derKey.equals("classification")) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Position literals first in String comparisons](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:51 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 7
- Added 3
           
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212&bid=16856521)

2020-03-05 18:51 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static Response listDerivates(UriInfo info, String mcrId, String format,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'listDerivates(UriInfo, String, String, String)' has an NPath complexity of 3240](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:51 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static MCRObjectID retrieveMCRDerivateID(MCRObjectID parentObjId, String paramDerID)
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'retrieveMCRDerivateID(MCRObjectID, String)' has an NPath complexity of 8100](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-05 18:51 UTC, adlerre commented on mycore-restapi/src/main/java/org/mycore/restapi/v1/utils/MCRRestAPIObjectsHelper.java
> +    public static Response listDerivates(UriInfo info, String mcrId, String format,
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Avoid really long methods.](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5129212)

2020-03-25 10:59 UTC, yagee-de requested changes

2020-03-25 10:59 UTC, yagee-de commented on mycore-restapi/src/main/java/org/mycore/restapi/MCRRestAuthorizationFilter.java
> +                    MCRRestAPIObjectsHelper.retrieveMCRDerivateID(MCRObjectID.getInstance(optObjId.get()), derId))
Write a [PreMatching Filter](https://www.logicbig.com/tutorials/java-ee-tutorial/jax-rs/filters-pre-matching.html) and register it within `org.mycore.restapi.v1.MCRRestV1App` to rewrite the URL on-the-fly without tighter coupling (read: leave `MCRRestAuthorizationFilter` untouched)

2020-04-01 17:38 UTC, rsteph-de commented
will use Jersey prematching filter as suggested

2020-04-01 17:38 UTC, closed without merging