MCR-2192 mycore csl
MyCoRe-Org/mycore pull request #953
Opened 2020-04-22 12:38 UTC by sebhofmann

[Link to jira](https://mycore.atlassian.net/browse/MCR-2192).

2020-04-22 12:40 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5401931&bid=17708596)

2020-04-23 08:05 UTC, fluetze approved these changes
Looks good. Thx!

2020-04-23 13:02 UTC, kkrebs commented
please fix build errors:

[WARNING] Unused declared dependencies found:
[WARNING]    org.citationstyles:locales:jar:2.0.0:compile
[WARNING]    org.citationstyles:styles:jar:2.0.0:compile

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-dependency-plugin:3.1.1:analyze-only (analyze) on project mycore-csl: Dependency problems found -> [Help 1]
[ERROR]

2020-04-27 09:08 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5401931&bid=17708596)

2020-04-27 10:06 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5401931&bid=17708596)

2020-04-27 14:51 UTC, yagee-de requested changes

2020-04-27 14:51 UTC, yagee-de commented on mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java
> +        final String style =  parameter!=null? parameter.getParameter("style", DEFAULT_STYLE): DEFAULT_STYLE;
please check code style

2020-04-27 14:51 UTC, yagee-de commented on mycore-csl/src/main/resources/components/csl/config/mycore.properties
> +# MCR.ContentTransformer.mods2bibtex.Command=%UBO.BibUtils.Base%xml2bib -b -w -o UTF8
Do not use properties that are not defined elsewhere

2020-04-27 14:51 UTC, yagee-de commented on mycore-csl/src/main/resources/components/csl/config/mycore.properties
> +# MCR.ContentTransformer.mods2bibtex.Command=%UBO.BibUtils.Base%xml2bib -b -w -o UTF8
How about removing properties from mycore-mods and add a comment:
#requires runtime dependency mycore-mods and including the last 3 lines as active properties

2020-04-29 12:11 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- mycore-csl/src/main/java/org/mycore/csl/MCRBibTeXCSLTransformer.java  7
- mycore-csl/src/main/java/org/mycore/csl/MCRItemDataProvider.java  3
- mycore-csl/src/main/java/org/mycore/csl/MCRCSLTransformerInstance.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5401931&bid=17708596)

2020-04-30 18:03 UTC, merged