MCR-2175 resolve thumbnails in IIIF-API
MyCoRe-Org/mycore pull request #955
Opened 2020-04-27 10:10 UTC by rsteph-de

[Link to jira](https://mycore.atlassian.net/browse/MCR-2175).

2020-04-27 10:13 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-04-27 10:13 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    public static BufferedImage getThumbnail(int thumbnailSize, Path pdfFile, boolean centered) throws IOException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'getThumbnail(int, Path, boolean)' has an NPath complexity of 417](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-27 10:23 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-04-27 10:23 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    public static BufferedImage getThumbnail(int thumbnailSize, Path pdfFile, boolean centered) throws IOException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'getThumbnail(int, Path, boolean)' has an NPath complexity of 417](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-27 11:49 UTC, sebhofmann commented
What is wrong with this PR:
- Extra code for tiling is added, which is not using the iview job api.   
- iview iiif impl now decides what is the thumbnail, why not make a extra impl. for that decision.
- we generate iview files for pdf pages, seems like a little bit overkill. 

We should keep things simple in mycore-iview. 
In my opinion the pdf stuff belongs to mycore-media.
We need one IIIF impl. that does PDF, one impl that does iview and one which just delegates to the others for a mycore object.

2020-04-27 12:46 UTC, rsteph-de commented
>     * extra code for tiling is added, which is not using the iview job api.
I was not able to get this working ...
Iview Job API needs a physical image file - you cannot pass the thumbnail as BufferedImage, ...
since all metadata for the job needs to be stored within database. This is limited and e.g. I did not find an easy solution to cleanup afterwards.

>     * iview iiif impl now decides what is the thumbnail, why not make a extra impl. for that decision.
There is already an interface MCRTileFileProvider
which is implemented by iview and can be reimplemented in other applications.
I wanted to keep things "together" and added a 2nd method for thumbnail retrieval.
For thumbnail generation it is possible to implement your own eventhandler if needed.
> 
>     * we generate iview files for pdf pages, seems like a little bit overkill.
> 
I did not want to do it in the first place, but doing it differently whould need a lot more code changes in the IIIF implementation which relies on tiles. On the other side this allows as to handle larger thumbnails - think of them more as "title page" images , which can also serve as thumbnail ;-) 

> We should keep things simple in mycore-iview.
Agreed

> In my opinion the pdf stuff belongs to mycore-media.
I thought myore-media primarily contains code for handling audio and video, which may not be used in all repositories. This may lead to other dependencies in code and configuration. Therefore I did not want to mix that with PDF handling.
I tried to avoid a new dependency from mycore-iiif to mycore-media. And most of the code for PDF thumbnail generation was already part of mycore-iview2.

>
> We need one IIIF impl. that does PDF, one impl that does iview and one which just delegates to  the others for a mycore object.
>
This is a bigger task that should not be handled in this PR, but separately.
When implementing this, we might consider doing some things differently and do further optimization.

2020-04-27 12:53 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    public static BufferedImage getThumbnail(int thumbnailSize, Path pdfFile, boolean centered) throws IOException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'getThumbnail(int, Path, boolean)' has an NPath complexity of 417](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-27 12:53 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-04-27 13:50 UTC, sebhofmann commented
> Iview Job API needs a physical image file - you cannot pass the thumbnail as BufferedImage,
You already create a temp png file.

 > I thought myore-media primarily contains code for handling audio and video, which may not be used in all repositories. This may lead to other dependencies in code and configuration. Therefore I did not want to mix that with PDF handling.

Then we should consider a mycore-pdf component.

> There is already an interface MCRTileFileProvider
> which is implemented by iview and can be reimplemented in other applications.
> I wanted to keep things "together" and added a 2nd method for thumbnail retrieval.
> For thumbnail generation it is possible to implement your own eventhandler if needed.

Yes, but the problem is much more generic than iview. There could also be Thumbnails for Videos, Audio or any other file type. MCRTileFileProvider is only there to tell mycore where to get the .iview files.

2020-04-28 11:57 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-04-28 11:57 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    public static BufferedImage getThumbnail(int thumbnailSize, Path pdfFile, boolean centered) throws IOException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'getThumbnail(int, Path, boolean)' has an NPath complexity of 417](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-30 11:17 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 5
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  7
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java  3
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-04-30 11:17 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java
> +    private static Logger LOGGER = LogManager.getLogger();
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-30 11:17 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java
> +    public static final String DERIVATE_PARAMETER = "derivate";
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-30 11:17 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java
> +    public void rollback() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Document empty method body](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-30 11:17 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java
> +    private static List<String> derivateTypesForContent = MCRConfiguration2
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Fields should be declared at the top of the class, before any method declarations, constructors, initializers or inner classes.](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-04-30 11:17 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    public static BufferedImage getThumbnail(int thumbnailSize, Path pdfFile, boolean centered) throws IOException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'getThumbnail(int, Path, boolean)' has an NPath complexity of 417](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-05-05 16:06 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 2
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java  3
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  7
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-05-05 16:06 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java
> +    public void rollback() {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [Document empty method body](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-05-05 16:06 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    public static BufferedImage getThumbnail(int thumbnailSize, Path pdfFile, boolean centered) throws IOException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'getThumbnail(int, Path, boolean)' has an NPath complexity of 417](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-05-05 16:21 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java  3
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  7
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-05-07 13:03 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java  3
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  7
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-05-07 13:03 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    public static BufferedImage getThumbnail(int thumbnailSize, Path pdfFile, boolean centered) throws IOException {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'getThumbnail(int, Path, boolean)' has an NPath complexity of 417](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-05-07 15:47 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  7
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java  3
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-05-07 15:47 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    private static BufferedImage scalePage(int thumbnailSize, boolean centered, BufferedImage level1Image) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'scalePage(int, boolean, BufferedImage)' has an NPath complexity of 208](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-05-08 07:19 UTC, yagee-de requested changes

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java
> +                                .map(x -> (Element) x)
How about:
```
.filter(Element.class::isInstance)
.map(Element.class::cast)
```

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java
> +        if (MCRObjectID.isValid(id)) {
invert check and return early

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java
> +                        Optional<String> derType = derLink.getContentList().stream()
Do not use streams here if you know where to look for. Use JDOM methods directly and your code is clearly better understandable.

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java
> +                            Optional<String> oMainDoc = derLink.getContentList().stream()
Please use JDOM API to get to main. If in doubt use an XPath.

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java
> +                // Files.deleteIfExists(pImg);
What about this comment?

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRThumbnailTileInfoProvider.java
> +public interface MCRThumbnailTileInfoProvider {
There is literately not a single line of JavaDocs for this interface or its method!

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java
> +        .getOrThrow("MCRIIIFImage.Iview.ThumbnailForPdfEventHandler.Derivate.Types",
Does not seem to be a MCR.* property, why?

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java
> +            .getOrThrow("MCRIIIFImage.Iview.Thumbnail.Derivate.Types", MCRConfiguration2::splitValue)
Why not use MCR.* as property?

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java
> +            Optional<MCRTileFileProvider> optTFP = MCRConfiguration2.getInstanceOf(tileFileProviderClassName);
getInstanceOf() uses a property name and not a className as parameter. You might want to use instantiateClass() instead.

2020-05-08 07:19 UTC, yagee-de commented on mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java
> +                    .getInstanceOf(thumbnailTileInfoProviderClassName);
Same here use instantiateClass()

2020-05-12 09:47 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
- Added 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java  3
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  6
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-05-12 09:47 UTC, adlerre commented on mycore-iview2/src/main/java/org/mycore/iview2/frontend/MCRPDFTools.java
> +    private static BufferedImage scalePage(int thumbnailSize, boolean centered, BufferedImage level1Image) {
![Codacy](https://app.codacy.com/assets/images/favicon.png) Issue found: [The method 'scalePage(int, boolean, BufferedImage)' has an NPath complexity of 208](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159)

2020-05-12 09:55 UTC, adlerre commented
![Codacy](https://app.codacy.com/assets/images/favicon.png) Here is an overview of what got changed by this pull request:


```diff

Issues
======
+ Solved 1
           

Complexity increasing per file
==============================
- mycore-iview2/src/main/java/org/mycore/iview2/iiif/MCRIVIEWIIIFImageImpl.java  2
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRDefaultThumbnailTileInfoProvider.java  6
- mycore-iview2/src/main/java/org/mycore/iview2/backend/MCRPDFThumbnailJobAction.java  3
- mycore-iview2/src/main/java/org/mycore/iview2/events/MCRThumbnailForPdfEventHandler.java  5
         
```


See the complete overview on [Codacy](https://app.codacy.com/manual/MyCoRe/mycore/pullRequest?prid=5425159&bid=17791799)

2020-05-12 10:44 UTC, merged